### ISSUE TITLE
Add a git rev option in source install

### ISSUE THREAD

**Issue by BarthV** [neillturner/kitchen-ansible#103]
https://github.com/neillturner/kitchen-ansible/blob/master/lib/kitchen/provisioner/ansible_playbook.rb#L348

* Currently we are using the git master only

Is it possible tu add a new attribut `"source_rev"` that allow us to checkout a specific rev/tag ? (default would be `HEAD` ?

Thanks

**Comment by neillturner** [comment]
in release 0.0.31

**Comment by BarthV** [comment]
:yum: thanks !
