### ISSUE TITLE
sudo: ansible-playbook: command not found

### ISSUE THREAD

**Issue by jblackburn22** [neillturner/kitchen-ansible#106]
Periodically test-kitchen failed since it can't find ansible-playbook.  Below is a copy of the debug messages.

       Going to invoke ansible-playbook with: sudo -E ansible-playbook --inventory-file=/tmp/kitchen/hosts -c local -M /tmp/kitchen/modules        /tmp/kitchen/default.yml
D      [SSH] ec2-user@172.21.79.27<{:user_known_hosts_file=>"/dev/null", :paranoid=>false, :port=>22, :compression=>true, :compression_level=>6, :keepalive=>true, :keepalive_interval=>60, :timeout=>20, :keys_only=>true, :keys=>["/opt/jenkins/jobs/01.01-ansible-tests/workspace/jenkins/test-kitchen.pem"], :auth_methods=>["publickey"], :user=>"ec2-user"}> (sudo -E ansible-playbook --inventory-file=/tmp/kitchen/hosts -c local -M /tmp/kitchen/modules        /tmp/kitchen/default.yml)
       sudo: ansible-playbook: command not found
D      Cleaning up local sandbox in /tmp/default-amazon-sandbox-20151204-25180-1eiztv
Converge failed on instance <default-amazon>.
Please see .kitchen/logs/default-amazon.log for more details
------Exception-------
Class: Kitchen::ActionFailed
Message: SSH exited (1) for command: [sudo -E ansible-playbook --inventory-file=/tmp/kitchen/hosts -c local -M /tmp/kitchen/modules        /tmp/kitchen/default.yml]
----------------------
D      Converge failed on instance <default-amazon>.
D      ------Exception-------
D      Class: Kitchen::InstanceFailure
D      Message: Converge failed on instance <default-amazon>.  Please see .kitchen/logs/default-amazon.log for more details
D      ---Nested Exception---
D      Class: Kitchen::ActionFailed
D      Message: SSH exited (1) for command: [sudo -E ansible-playbook --inventory-file=/tmp/kitchen/hosts -c local -M /tmp/kitchen/modules        /tmp/kitchen/default.yml]
D      ------Backtrace-------
D      /opt/jenkins/home/.rvm/gems/ruby-2.2.1/gems/test-kitchen-1.4.2/lib/kitchen/provisioner/base.rb:74:in `rescue in call'
D      /opt/jenkins/home/.rvm/gems/ruby-2.2.1/gems/test-kitchen-1.4.2/lib/kitchen/provisioner/base.rb:77:in `call'
D      /opt/jenkins/home/.rvm/gems/ruby-2.2.1/gems/test-kitchen-1.4.2/lib/kitchen/instance.rb:366:in `block in converge_action'
D      /opt/jenkins/home/.rvm/gems/ruby-2.2.1/gems/test-kitchen-1.4.2/lib/kitchen/instance.rb:488:in `call'
D      /opt/jenkins/home/.rvm/gems/ruby-2.2.1/gems/test-kitchen-1.4.2/lib/kitchen/instance.rb:488:in `synchronize_or_call'
D      /opt/jenkins/home/.rvm/gems/ruby-2.2.1/gems/test-kitchen-1.4.2/lib/kitchen/instance.rb:453:in `block in action'
D      /home/jenkins/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/benchmark.rb:288:in `measure'
D      /opt/jenkins/home/.rvm/gems/ruby-2.2.1/gems/test-kitchen-1.4.2/lib/kitchen/instance.rb:452:in `action'
D      /opt/jenkins/home/.rvm/gems/ruby-2.2.1/gems/test-kitchen-1.4.2/lib/kitchen/instance.rb:362:in `converge_action'
D      /opt/jenkins/home/.rvm/gems/ruby-2.2.1/gems/test-kitchen-1.4.2/lib/kitchen/instance.rb:341:in `block in transition_to'
D      /opt/jenkins/home/.rvm/gems/ruby-2.2.1/gems/test-kitchen-1.4.2/lib/kitchen/instance.rb:340:in `each'
D      /opt/jenkins/home/.rvm/gems/ruby-2.2.1/gems/test-kitchen-1.4.2/lib/kitchen/instance.rb:340:in `transition_to'
D      /opt/jenkins/home/.rvm/gems/ruby-2.2.1/gems/test-kitchen-1.4.2/lib/kitchen/instance.rb:160:in `verify'
D      /opt/jenkins/home/.rvm/gems/ruby-2.2.1/gems/test-kitchen-1.4.2/lib/kitchen/instance.rb:189:in `block in test'
D      /home/jenkins/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/benchmark.rb:288:in `measure'
D      /opt/jenkins/home/.rvm/gems/ruby-2.2.1/gems/test-kitchen-1.4.2/lib/kitchen/instance.rb:185:in `test'
D      /opt/jenkins/home/.rvm/gems/ruby-2.2.1/gems/test-kitchen-1.4.2/lib/kitchen/command.rb:176:in `public_send'
D      /opt/jenkins/home/.rvm/gems/ruby-2.2.1/gems/test-kitchen-1.4.2/lib/kitchen/command.rb:176:in `block (2 levels) in run_action'
D      ----------------------
zlib(finalizer): the stream was freed prematurely.

Ansible was installed via pip using cloud-init. 

ec2-user@ip-172-21-79-27 ~]$ which ansible-playbook
/usr/bin/ansible-playbook

Looking at /var/log/secure, it looks like the sudo command wasn't run.

Dec  4 20:43:24 ip-172-21-79-27 sudo: ec2-user : TTY=pts/0 ; PWD=/home/ec2-user ; USER=root ; COMMAND=/bin/cp /tmp/kitchen/ansible.cfg /etc/ansible
Dec  4 20:43:24 ip-172-21-79-27 sudo: ec2-user : TTY=pts/0 ; PWD=/home/ec2-user ; USER=root ; COMMAND=/bin/cp -r /tmp/kitchen/group_vars /etc/ansible/.
Dec  4 20:43:24 ip-172-21-79-27 sudo: ec2-user : TTY=pts/0 ; PWD=/home/ec2-user ; USER=root ; COMMAND=/bin/cp -r /tmp/kitchen/host_vars /etc/ansible/.
Dec  4 20:43:24 ip-172-21-79-27 sshd[2413]: pam_unix(sshd:session): session closed for user ec2-user

Do you have any suggestions for how I can isolated what's happening?

**Comment by jblackburn22** [comment]
I'm wondering if it's a timing problem where test-kitchen is starting before the userdata has finished to complete.

This is the last Ansible install message from /var/log/secure.
Dec  4 20:43:24 ip-172-21-79-27 sudo: ec2-user : TTY=pts/0 ; PWD=/home/ec2-user ; USER=root ; COMMAND=/bin/cp -r /tmp/kitchen/host_vars /etc/ansible/.

This is the timestamp of when the cloud-init finished.
Cloud-init v. 0.7.2 finished at Fri, 04 Dec 2015 20:43:38 +0000. Datasource DataSourceEc2.  Up 155.84 seconds

Note that there is a gap of 12 seconds.

I'm going to workaround the issue by installing Ansible via omnibus installer.  Previously it was being installed by the cloud-init (EC2 userdata).

**Comment by neillturner** [comment]
you can modify the ansible_playbook.rb  code to insert a sleep command to test your theory: 
change 
    cmd = ansible_command("ansible-playbook")
to 
   cmd = ansible_command("sleep 30:ansible-playbook")
I can always add a new parameter 
   ansible_playbook_command
which would allow folks to specify the install command they would like which means you could add the sleep command to the ansible playbook command.

**Comment by neillturner** [comment]
closing as i'm assume he is using workaround.

**Comment by pburkholder** [comment]
s/he/she/
