### ISSUE TITLE
Ansible fails to install from apt repo if ansible.cfg is present

### ISSUE THREAD

**Issue by DXist** [neillturner/kitchen-ansible#107]
If you have ansible.cfg ansible installation from apt is failed due to the prompt:
```
Configuration file '/etc/ansible/ansible.cfg'
==> File on system created by you or by a script.
==> File also in package provided by package maintainer.
What would you like to do about it ? Your options are:
Y or I : install the package maintainer's version
N or O : keep your currently-installed version
D : show the differences between the versions
Z : start a shell to examine the situation
The default action is to keep your current version.
```

**Comment by mheap** [comment]
@DXist Could you provide more details? Which operating system are you using?

I was unable to reproduce this with Ubuntu 15.04. The installation script kept my currently installed version and didn't prompt

**Comment by DXist** [comment]
Sorry for not providing details. I use Debian 8.2 Docker image. Probably, it has different apt configuration then in Ubuntu. I didn't try to converge Debian host on Vagrant.

**Comment by neillturner** [comment]
there is support for debian. 
have to tried setting 
   ansible_platform: debian.
if you run with option -l debug 
you'll get debug messages so we can see what's happening

**Comment by DXist** [comment]
Hmm, I wasn't able to reproduce it again in fresh environment. Sorry for taking your time.
