### ISSUE TITLE
Support for platforms/operating systems without package managers

### ISSUE THREAD

**Issue by wilkko** [neillturner/kitchen-ansible#108]
Promise for Ansible was that it does not require agent on the target machine. This makes Ansible ideal for operating systems like CoreOS, where there is no package manager and everything has to run on containers. Kitchen-ansible wants to install Ansible locally to the target machine to do provisioning.

Vagrant has implemented their Ansible provisioner so that Ansible doesn't need to be installed to the target machine. Is something similar possible with kitchen-ansible?

**Comment by neillturner** [comment]
Some folks are running kitchen-ansible to create a server to run ansible and pass an inventory file which points to one of more other servers that they provision. These servers don't get ansible installed on them.

 So yes you can just create a server to run ansible. You can even use vagrant to create the server to run ansible on your own host using the vagrant driver. 

 Another approach is to run ansible on your workstation directly, this is the approach of the kitchen-ansiblepush  provisioner. Although personally i prefer to keep my workstation as clean as possible so i prefer to run ansible in a vagrant on my host and then use host files to go to other servers.

**Comment by wilkko** [comment]
Thanks! Sounds like test-kitchen setup is doable with CoreOS as platform as well.

**Comment by wilkko** [comment]
Well you still need Chef or Ruby for the Busser and it that won't work with CoreOS.

**Comment by neillturner** [comment]
that's true but that is a test-kitchen issue not an issue with my provisioner. -) 
there is an issue for this: 
  https://github.com/test-kitchen/test-kitchen/issues/539
however it is probably possible to create a new busser that installs on the server that runs ansible 
and does serverspec tests in an ssh fashion to the hosts in the ansible hosts file. 
I have create a busser-ansiblespec already. we could look to enhance it to run serverspec tests in 'ssh mode'. see https://github.com/neillturner/busser-ansiblespec. 
 the easiest way to to specify parameters in the spec_helper that would tell it to use ssh mode and where to get the hosts file. It is probably not alot of code to create. more work to test. -)

**Comment by neillturner** [comment]
actually the easiest way to get this to work is to: 
-use test kitchen to create a server to just run ansible with a host file to another server.
-converge that server. 
-then run verify to install and run the busser-serverspec on the server that just runs ansible. 
then start changing the spec-helper to figure out what needs to be done to remotely do serverspec via ssh to another server. 
-then we can add it as options to busser-ansiblespec maybe

**Comment by neillturner** [comment]
this seems to show how to do remote tests with serverspec: 
  http://stackoverflow.com/questions/25642996/is-it-possible-to-include-common-tests-in-serverspec
just need to do this in busser-ansiblespec i think.

**Comment by wilkko** [comment]
+1 for ssh mode in ansiblespec/serverspec

**Comment by neillturner** [comment]
This now available with busser-ansiblespec version 0.6.0

**Comment by wilkko** [comment]
Will do after the holidays =)

**Comment by neillturner** [comment]
this is now supported using test-kitchen with the ssh connection option and with busser-ansiblespec for  remote ssh testing.
