### ISSUE TITLE
Coding Standards

### ISSUE THREAD

**Issue by mheap** [neillturner/kitchen-ansible#109]
Would you be open to receiving a pull request that updates `kitchen-ansible` to use `rubocop` to enforce coding standards?

**Comment by neillturner** [comment]
feel free. In fact i've had so many contributions other people have written more of the code than me which is a real success. -)

**Comment by mheap** [comment]
Great! I'll submit a PR once the existing PR (https://github.com/neillturner/kitchen-ansible/pull/110) is closed
