### ISSUE TITLE
Ansible doesn't install on Centos 7 platform

### ISSUE THREAD

**Issue by wilkko** [neillturner/kitchen-ansible#112]
Tried using kitchen-ansible with Centos 7 platform with both Vagrant and Docker drivers. Ansible fails to install on Centos 7:

```
      Error: Package: ansible-1.9.4-1.el6.noarch (epel)
           Requires: python-simplejson
       Error: Package: python-crypto2.6-2.6.1-2.el6.x86_64 (epel)
           Requires: libpython2.6.so.1.0()(64bit)
       Error: Package: python-httplib2-0.7.7-1.el6.noarch (epel)
           Requires: python(abi) = 2.6
           Installed: python-2.7.5-18.el7_1.1.x86_64 (@Updates)
               python(abi) = 2.7
               python(abi) = 2.7
           Available: python-2.7.5-16.el7.x86_64 (base)
               python(abi) = 2.7
               python(abi) = 2.7
       Error: Package: python-keyczar-0.71c-1.el6.noarch (epel)
           Requires: python(abi) = 2.6
           Installed: python-2.7.5-18.el7_1.1.x86_64 (@Updates)
               python(abi) = 2.7
               python(abi) = 2.7
           Available: python-2.7.5-16.el7.x86_64 (base)
               python(abi) = 2.7
               python(abi) = 2.7
       Error: Package: ansible-1.9.4-1.el6.noarch (epel)
           Requires: python(abi) = 2.6
           Installed: python-2.7.5-18.el7_1.1.x86_64 (@Updates)
               python(abi) = 2.7
               python(abi) = 2.7
           Available: python-2.7.5-16.el7.x86_64 (base)
               python(abi) = 2.7
               python(abi) = 2.7
       Error: Package: python-crypto2.6-2.6.1-2.el6.x86_64 (epel)
           Requires: python(abi) = 2.6
           Installed: python-2.7.5-18.el7_1.1.x86_64 (@Updates)
               python(abi) = 2.7
               python(abi) = 2.7
           Available: python-2.7.5-16.el7.x86_64 (base)
               python(abi) = 2.7
               python(abi) = 2.7
        You could try using --skip-broken to work around the problem
        You could try running: rpm -Va --nofiles --nodigest

Transferring files to <ansible-roles-centos-7>
Going to invoke ansible-playbook with: ANSIBLE_ROLES_PATH=/tmp/kitchen/roles sudo -E ansible-playbook --inventory-file=/tmp/kitchen/hosts -c local -M /tmp/kitchen/modules -vvv       /tmp/kitchen/default.yml
sudo: ansible-playbook: command not found
```

**Comment by neillturner** [comment]
see: https://github.com/neillturner/kitchen-ansible/blob/master/provisioner_options.md
did you set 
  ansible_yum_repo
to 
  http://dl.fedoraproject.org/pub/epel/7/x86_64/e/epel-release-7-5.noarch.rpm

**Comment by wilkko** [comment]
Of course I didn't =) Thanks for pointing that out. I got over installing Ansible, but now get this error:
  driver:
    name: docker

  provisioner:
    hosts: test-kitchen
    name: ansible_playbook
    playbook: test/integration/default.yml
    require_chef_for_busser: false
    require_ruby_for_busser: true
    ansible_verbose: true
    ansible_verbosity: 3
    ansible_yum_repo: http://dl.fedoraproject.org/pub/epel/7/x86_64/e/epel-release-7-5.noarch.rpm

  platforms:
    - name: centos-7.1

  verifier:
    ruby_bindir: '/usr/bin'

  suites:
    - name: ansible-roles

My .kitchen.yml is as follows:

  driver:
    name: docker

  provisioner:
    hosts: test-kitchen
    name: ansible_playbook
    playbook: test/integration/default.yml
    require_chef_for_busser: false
    require_ruby_for_busser: true
    ansible_verbose: true
    ansible_verbosity: 3
    ansible_yum_repo: http://dl.fedoraproject.org/pub/epel/7/x86_64/e/epel-release-7-5.noarch.rpm

  platforms:
    - name: centos-7.1

  verifier:
    ruby_bindir: '/usr/bin'

  suites:
    - name: ansible-roles

**Comment by neillturner** [comment]
serverspec should only be installed when you run the verify so
what have you specified at directory 
    test/integration

**Comment by wilkko** [comment]
```
test
└── integration
    ├── ansible-roles
    │   └── ansiblespec
    │       └── localhost
    │           └── default_spec.rb
    └── default.yml
```

**Comment by neillturner** [comment]
have a look at
 https://github.com/neillturner/busser-ansiblespec
and 
https://github.com/neillturner/ansible_repo

**Comment by neillturner** [comment]
version 0.0.34 will by default install ansible correctly for centos 7. closed
