### ISSUE TITLE
ansible_version ignored?

### ISSUE THREAD

**Issue by danrue** [neillturner/kitchen-ansible#124]
Ansible released 2.0 and my tests are failing, despite setting ansible_version to 1.9.2. Is it possible that kitchen-ansible is not properly respecting ansible_version? I tried running the integration_test to reproduce this, but it didn't seem to work either. 

Looking for confirmation that this is a kitchen-ansible problem, or if somehow I am not specifying the version correctly.

**Comment by metmajer** [comment]
Confirmed two ways: Ansible 2.0 totally broken and ansible_version can't resolve.

**Comment by neillturner** [comment]
i have not looked at ansible 2.0 however if you post the relevant .kitchen.yml code then i can reproduce. you can also add -l debug to your kitchen command to get debug output that can help. 
  kitchen converge xxxx -l debug. 
there are lots of ways you can install ansible - from the repo, from source, using omnibus ansible. usually if folks are having a problem with installing ansible then they re able to workaround it by  installing using one of the other ways.

**Comment by danrue** [comment]
Can you help get https://github.com/neillturner/kitchen-ansible/blob/master/integration_test/.kitchen.yml working? If that works I can reproduce there by specifying ansible_version after line 8. (and if that integration_test works for you, let me know and I'll fix whatever local problem I have).

**Comment by rndmh3ro** [comment]
Using [this](https://github.com/hardening-io/ansible-os-hardening/blob/ansible_2.0/.kitchen.yml) .kitchen.yml, kitchen-ansible works with 2.0.0.1 for me.

**Comment by danrue** [comment]
The issue isn't 2.0.0.1 support. It's 1.9.4 support. Anyone have a working example of that?

**Comment by rndmh3ro** [comment]
Sorry, mixup on my side, @danrue.

However I can confirm the problem with [this](https://github.com/hardening-io/ansible-os-hardening/blob/master/.kitchen.yml) kitchen.yml, using ansible-omnibus.
Here's the debug gist:
https://gist.github.com/rndmh3ro/093f847cc60539c75503

I guess the problem seems to be [here](https://github.com/neillturner/omnibus-ansible/blob/master/ansible_install.sh#L4), resulting in this error:
https://gist.github.com/rndmh3ro/093f847cc60539c75503#file-kitchen-debug-log-L65

Next problem is that in the omnibus-script it is checked if `"$1" == "-v"`(https://github.com/neillturner/omnibus-ansible/blob/master/ansible_install.sh#L4), but in the provisioner `version` is set to `-v 1.9.2` thus making the comparion not working.
Also: /bin/sh does not support `==` comparisions, see [here](http://stackoverflow.com/a/3411105).

**Comment by lobsterdore** [comment]
Seeing the same issue here, ansible_version does not seem to work at all. Also shouldn't the version work with the package manager style install as well as pip style? Looking at the source it seems to get ignored completely when using apt or yum.

**Comment by neillturner** [comment]
i'll test this when i get a chance

**Comment by kireevco** [comment]
Still having same issue on MacOS.

**Comment by neillturner** [comment]
While actually this is no support for MacOs at the moment we only install on linux flavours but support configuring windows and macos via ssh connection from linux box running ansible to a third server run windows or macos.

**Comment by zihaoyu** [comment]
Looks like Ansible 1.9.x versions are broken on Centos. I'm getting:
```
No package ansible-1.9.4 available.
```

Looking at the [EPEL repo](https://dl.fedoraproject.org/pub/epel/7/x86_64/a/), it seems like Ansible 1.9.4 package has been renamed to `ansible1.9-1.9.4`, compared to `ansible-2.0.1.0`. Could that be the reason of failures?

In fact when I do the yum search, I see the following:
```
ansible-inventory-grapher.noarch : Creates graphs representing ansible inventory
ansible-lint.noarch : Best practices checker for Ansible
ansible-openstack-modules.noarch : Unofficial Ansible modules for managing Openstack
ansible.noarch : SSH-based configuration management, deployment, and task execution system
ansible1.9.noarch : SSH-based configuration management, deployment, and task execution system
```

**Comment by neillturner** [comment]
thanks for your comments. I haven't looked much at ansible 2.x as i was waiting for it to "settle" down but i will try and figure this out.

**Comment by zihaoyu** [comment]
Thanks @neillturner !
