### ISSUE TITLE
Question: why forcing Ruby version with .ruby-version file?

### ISSUE THREAD

**Issue by walterdolce** [neillturner/kitchen-ansible#128]
Hi, 
I was wondering why the project forces contributors to have Ruby 2.1.5?

**Comment by trumant** [comment]
The .ruby-version is present only to signal that Ruby is required to run the specs locally. You'll note that 2.1.5 is the most recent Ruby used by TravisCI as well: https://github.com/neillturner/kitchen-ansible/blob/master/.travis.yml

**Comment by walterdolce** [comment]
I see. Though I believe this is a matter of environment setup, which can obviously vary from engineer to engineer.

For example I cloned the kitchen-ansible repository and I have deleted the current `.ruby-version` file with `2.1.5` in it. I have specified to `2.3.0` via `rbenv` and the specs ran just fine.

I see it was added in https://github.com/neillturner/kitchen-ansible/commit/1ac961c2d7fc9b28fccdf2ee13772d2a075ba94a after #35 was raised, which again seems to be a matter of environment setup.

What do you think?

I am happy to send over a PR to remove it.

**Comment by neillturner** [comment]
well the specs are really designed so when you push a branch then the tests are run in travis rather than being able to run them on your workstation.

**Comment by walterdolce** [comment]
Sure. So there no need to force the Ruby version to use to others and it can be removed?

**Comment by neillturner** [comment]
closing as Avoid forcing Ruby version #129 merged and released

**Comment by walterdolce** [comment]
![img](http://www.sharegif.com/wp-content/uploads/2014/03/giphy41.gif)
