### ISSUE TITLE
Custom install command

### ISSUE THREAD

**Issue by rndmh3ro** [neillturner/kitchen-ansible#133]
Is it possible that you add the "custom_install_command" function to kitchen-ansible, like you did with the puppet provisioner?

**Comment by neillturner** [comment]
you can do that with the ansible_playbook_command .kitchen.yml parameter

**Comment by rndmh3ro** [comment]
Seems like a misunderstanding on my part. I actually thought this command would be executed as a last step in converging, not _instead_ of a custom install command.
Thanks for your answer, though!
