### ISSUE TITLE
Why ansible must be tested using localhost?

### ISSUE THREAD

**Issue by vantt** [neillturner/kitchen-ansible#137]
Hi,

May be a stupid question, but I don't understand the philosophy behind of why we must install ansible and copy all of required roles, playbook to provisioned host and run it as local ?

Since ansible can manipulate remote machine, this way of implementation make me a little bit confused. Is there any limitation or philosophy for this decision ?

Thanks.

**Comment by neillturner** [comment]
Well the idea is to not pollution your workstation with an ansible install and if you are running a windows station you can't install ansible on it and many corporates where I contract force you to use windows workstations. -) 
 By creating another server and then installing ansible and doing localhost you can do iterative development of your ansible scripts and throw the server away after use and you just have the ansible repo on your workstation. If you use kitchen-ssh or kitchen-sync it is very quick to copy the files.  
 I also support using ssh so then when your server just runs ansible and then goes out to one or more third party servers. 
 Finally i have build a serverspec kitchen verifier that will run on your workstation (or remotely on the box) to do the verify step. 
 Hope that's helpful. 
 Always open to contributions. I try and put them in quickly and turn them around -)

**Comment by vantt** [comment]
Yeah, I understand your situation. I've never worked with an windows workstation and willing to have ansible on my machine with the other system as well as test-kitchen and kitchen-ansible.

The only problem I see is by installing ansible on a remote machine, it changes my machine environment  and makes testing a little bit inconsistent. 

Thanks

**Comment by neillturner** [comment]
i think the other provisioner - ansiblepush is designed to run natively on your workstation although i would try and sort out why " installing ansible on a remote machine, it changes my machine environment and makes testing a little bit inconsistent".... Personally I use vagrant and vm alot to test out different things like different version of stuff as it keeps my workstation cleaner-)

**Comment by vantt** [comment]
Let's give an example, installing ansible will install additional packages like epel on that machine. And my role's duty is to install epel, so it makes harder to verify the situation.

**Comment by neillturner** [comment]
well then you can use connection ssh and have 2 servers on that run ansible and a second that you configure -).  I demonstrate this on my blog 
 http://ec2dream.blogspot.co.uk/2015/12/automated-devops-with-test-kitchen.html

**Comment by neillturner** [comment]
closing

**Comment by neillturner** [comment]
version 0.0.39 support dynamic inventory now this might work if the inventory file has a #! at the front and denotes what to execute.
