### ISSUE TITLE
Error while executing jinja2 template

### ISSUE THREAD

**Issue by gvenka008c** [neillturner/kitchen-ansible#138]
Hi,

We have all our unusable playbook which runs against openstack dynamic inventory.

I have the below zk.j2 file under templates which gets mesos_masters from dynamic inventory.

zk://
{%- for host in groups['mesos_masters'] -%}
{{ hostvars[host]['ansible_ssh_host'] }}:2181{% if not loop.last %},{% endif %}
{%- endfor -%}
/mesos

When I run this through test kitchen, i am seeing the below error. 
TASK: [mesos_slave | update slave to point to zk nodes] ***********************
EXEC ['/bin/sh', '-c', 'mkdir -p $HOME/.ansible/tmp/ansible-tmp-1456946091.66-70813072314814 && echo $HOME/.ansible/tmp/ansible-tmp-1456946091.66-70813072314814']
fatal: [localhost] => {'msg': "AnsibleUndefinedVariable: One or more undefined variables: 'dict object' has no attribute 'mesos_masters'", 'failed': True}

How can i fix this? Let me know if any details required. Thanks.

Thanks,
Govind

**Comment by neillturner** [comment]
if you can give me the relevant part of your .kitchen.yaml file and maybe some test case that would be helpful. It would be useful to know if you are running with connection local or ssh.

**Comment by gvenka008c** [comment]
@neillturner Here is the .kitchen.yml 

---
driver:
  name: openstack 
  openstack_username: <%= ENV['OS_USERNAME'] %>
  openstack_api_key: <%= ENV['OS_PASSWORD'] %>
  openstack_auth_url: <%= ENV['OS_AUTH_URL'] %>/tokens
  openstack_tenant: <%= ENV['OS_TENANT_NAME'] %>
  openstack_region: <%= ENV['OS_REGION_NAME'] %>
  key_name: <%= ENV['OS_KEY_NAME'] %>
  image_ref: "8ed15196-ab90-42cc-9aa3-fb7072130563"
  flavor_ref: "102"
  network_ref: /Public_Agile|Public_AGILE/
  private_key_path: xplat 
  server_name: kitchen_mesos_slave
  no_ssh_tcp_check: true
  no_ssh_tcp_check_sleep: 20
  security_groups: [ jenkins_mesos ]

transport:
  ssh_key: xplat
  connection_timeout: 10
  connection_retries: 5
  username: clduser

provisioner:
  name: ansible_playbook
  ansible_verbose: true
  ansible_verbosity: 3
  require_chef_for_busser: false
  require_ruby_for_busser: true
  hosts: mesos-slave
  become: true

platforms:
  - name: mesos

verifier:
  ruby_bindir: '/usr/bin'

suites:
  - name: default
    run_list:
    attributes:

Let me know if any details required. Thanks.

**Comment by neillturner** [comment]
so you are doing the default connection
ansible_connection	local

so ansible is instead on the same server as you are building so it will only build the local server.

**Comment by gvenka008c** [comment]
@neillturner so how can i get around the j2 templates working?

**Comment by neillturner** [comment]
if they are remote to ansible you need to use: 
 ansible_connection: ssh

**Comment by gvenka008c** [comment]
@neillturner Try and ran into same error.

fatal: [localhost] => {'msg': "AnsibleUndefinedVariable: One or more undefined variables: 'dict object' has no attribute 'mesos_masters'", 'failed': True}
       fatal: [localhost] => {'msg': "AnsibleUndefinedVariable: One or more undefined variables: 'dict object' has no attribute 'mesos_masters'", 'failed': True}

**Comment by neillturner** [comment]
you will see the ansible command it does in the logs. i'm not sure if it supports dynamic hosts like this. 
I think it is just looking for mesos-slave in the hosts file. 
if you can figure out the command you need then we can enhance the ansible playbook command.

**Comment by gvenka008c** [comment]
@neillturner Thanks. Yes, for some reason kitchenci is not able to parse the jinja2 template ansible variables.

Here is the template

zk://
{%- for host in groups['mesos_masters'] -%}
{{ hostvars[host]['ansible_ssh_host'] }}:2181{% if not loop.last %},{% endif %}
{%- endfor -%}
/marathon

Here is the error
<localhost> EXEC ['/bin/sh', '-c', 'mkdir -p $HOME/.ansible/tmp/ansible-tmp-1457722371.16-171268709962868 && echo $HOME/.ansible/tmp/ansible-tmp-1457722371.16-171268709962868']
       fatal: [localhost] => {'msg': "AnsibleUndefinedVariable: One or more undefined variables: 'dict object' has no attribute 'ansible_ssh_host'", 'failed': True}
       fatal: [localhost] => {'msg': "AnsibleUndefinedVariable: One or more undefined variables: 'dict object' has no attribute 'ansible_ssh_host'", 'failed': True}

**Comment by gvenka008c** [comment]
@neillturner Is there a way i can force to make use of my dynamic inventory script? Seems like it reads only my static inventory file "hosts" while running kitchen verify. Is there a way to make use of both static + dynamic inventory?

--inventory-file=/tmp/kitchen/hosts

Going to invoke ansible-playbook with: ANSIBLE_ROLES_PATH=/tmp/kitchen/roles sudo -Es  ansible-playbook --inventory-file=/tmp/kitchen/hosts -c local -M /tmp/kitchen/modules -vvv        /tmp/kitchen/default.yml

**Comment by neillturner** [comment]
yes we need to make an enhancement to do this. I have recently been working on adding windows support but i will try and implement dynamic inventories this next week.

**Comment by neillturner** [comment]
version 0.0.39 support dynamic inventory now this might work if the inventory file has a #! at the front and denotes what to execute.
