### ISSUE TITLE
require_ruby_for_busser fails on Ubuntu >= 14.10 due to default ruby version

### ISSUE THREAD

**Issue by svend** [neillturner/kitchen-ansible#144]
The default ruby version on Ubuntu 14.10 and newer is 2.1 [1], this causes kitchen verify to fail because the ruby-1.9.1-dev package is installed, but the 2.1 dev package is not installed.

Two fixes that seem to work are:
1) Install ruby-2.1 packages (this is what kitchen-ansible does on Debian >= 8)
2) Run update-alternatives to make ruby point to ruby1.9 (this is what kitchen-ansible does on Debian == 6)

Any thoughts? This commit implements fix 1):

https://github.com/svend/kitchen-ansible/commit/e05c5315bc54258c6901d8494588abdd6ed7f5fa

Here is the output from a kitchen test run on Ubuntu 15.04. First the ruby1.9.1-dev package is installed:

```
       The following extra packages will be installed:
         libjs-jquery libruby1.9.1 libruby2.1 ruby ruby2.1 rubygems-integration
       Suggested packages:
         javascript-common ri ruby-dev ruby1.9.1-examples ri1.9.1 graphviz
         ruby-switch bundler
       The following NEW packages will be installed:
         libjs-jquery libruby1.9.1 libruby2.1 ruby ruby1.9.1 ruby1.9.1-dev ruby2.1
         rubygems-integration
       0 upgraded, 8 newly installed, 0 to remove and 1 not upgraded.
       Need to get 6,788 kB of archives.
       After this operation, 32.1 MB of additional disk space will be used.
```

The verify phase is running ruby 2.1:

```
-----> Running serverspec test suite
-----> Installing Serverspec..
Fetching: rspec-support-3.5.0.beta3.gem (100%)
Fetching: rspec-core-3.5.0.beta3.gem (100%)
Fetching: diff-lcs-1.2.5.gem (100%)
Fetching: rspec-expectations-3.5.0.beta3.gem (100%)
Fetching: rspec-mocks-3.5.0.beta3.gem (100%)
Fetching: rspec-3.5.0.beta3.gem (100%)
Fetching: rspec-its-1.2.0.gem (100%)
Fetching: multi_json-1.11.2.gem (100%)
Fetching: bcrypt_pbkdf-1.0.0.alpha1.gem (100%)
       Building native extensions.  This could take a while...
       /usr/lib/ruby/2.1.0/rubygems/ext/builder.rb:89:in `run': ERROR: Failed to build gem native extension. (Gem::Ext::BuildError)
       
           /usr/bin/ruby2.1 extconf.rb
       mkmf.rb can't find header files for ruby at /usr/lib/ruby/include/ruby.h
       
       extconf failed, exit code 1
       
       Gem files will remain installed in /tmp/verifier/gems/gems/bcrypt_pbkdf-1.0.0.alpha1 for inspection.
       Results logged to /tmp/verifier/gems/extensions/x86_64-linux/2.1.0/bcrypt_pbkdf-1.0.0.alpha1/gem_make.out
```

[1] http://packages.ubuntu.com/vivid/ruby

**Comment by neillturner** [comment]
If you think that's the better way then create a PR And i will merge. I'm always happy to take contributions. 

Actually i have created a new verifier, kitchen-verifier-serverspec that's does use the busser and can do remote verify from your workstation so in this case you don't need ruby at all on the servers you are configuring. :)

**Comment by svend** [comment]
Thanks, I'll check out kitchen-verifier-serverspec!

I've created a PR to use ruby 2.1 on utopic and newer.
