### ISSUE TITLE
hosts file not respected after 0.0.38 (possible regression)

### ISSUE THREAD

**Issue by artburkart** [neillturner/kitchen-ansible#146]
Hi, when I use version 0.0.38, kitchen-ansible respects the hosts directory I point to in `ansible.cfg`, however, when I use version 0.0.39 or later, it injects its own host file that looks like

```ini
localhost ansible_connection=local
[localhost]
localhost
```

which results in 

```command
PLAY ***************************************************************************
       skipping: no hosts matched
```

when I run `kitchen converge`. 

I looked at the [diff between version 0.0.38 and 0.0.39](https://github.com/neillturner/kitchen-ansible/compare/0.0.38...0.0.39) and it appears some work was down around hosts, but it's not clear how I'm supposed to use kitchen-ansible moving forward. If this is something obvious, could you please point me to its documentation?

Thanks!

**Comment by neillturner** [comment]
ok. its sometimes hard to handle all the different possibilities as a workaround i suggest configuring the parameter 
    ansible_inventory_file 
in kitchen.yml file to point to the hosts file that is in your  ansible.cfg. 
I will look at this case where you don't want a host file at all as it is in the ansible.cfg
behaviour. 
 0.0.39 added support for dynamic inventory and inventory directory. (ie you can have multiple inventory files in a directory or have a python script). there are lots of ways to do inventory -) 
i will try and re-install your case. let me know if workout works for you.

**Comment by neillturner** [comment]
Added a none option for ansible_inventory so you can force it to use the ansible_cfg. 
Closed

**Comment by artburkart** [comment]
For some reason I didn't get a ping for your message two days ago. I'll upgrade and let you know :) Thanks!
