### ISSUE TITLE
Gemfile.lock not in sync with the current gem version

### ISSUE THREAD

**Issue by karouf** [neillturner/kitchen-ansible#152]
In the `Gemfile.lock` file, `kitchen-ansible` is pinned to version 0.40.1 but the gemspec file specifies version 0.41.0
When I ran `bundle install` after cloning the repo in order to contribute, it updated a couple of gems which I found strange. I didn't want to include changes to the `Gemfile.lock` in my PRs so I cherry-picked but I thought maybe you'd like to know and that you'd prefer to update the pinned versions of the gems yourself, in case I was missing something.

**Comment by neillturner** [comment]
thanks for logging this i sometimes forget to update in the past the test would pick this up but we have lost this recently. fixed in 0.42.0.

**Comment by karouf** [comment]
No problem, glad I could help. And thanks for merging my PRs so quickly! :+1:
