### ISSUE TITLE
How do inherit default variables form my role?

### ISSUE THREAD

**Issue by kireevco** [neillturner/kitchen-ansible#153]
When I run my test I'd like to have all variables from defaults/vars in my test environment. Is there any built-in way to do so now?

Thank you.

**Comment by neillturner** [comment]
i assume by test you mean running the converge step not the test step running serverspec or something. 
is that an ansible supported way of setting variables? 
we support the standard ways of setting variables as per http://docs.ansible.com/ansible/playbooks_variables.html
as per https://github.com/neillturner/kitchen-ansible/blob/master/provisioner_options.md
group_vars_path
host_vars_path
extra_vars  parameter works from a hash specified in the kitchen.yml

i guess we could add an extra parameter 
extra_vars_path  that you could set to defaults/vars
how are the variables specified in defaults/vars

**Comment by neillturner** [comment]
try using the additional_copy_path  parameter. 
if this doesn't work re-open issue with a bit more info and i will look into it. 
closing
