### ISSUE TITLE
Support multiple role paths

### ISSUE THREAD

**Issue by lobsterdore** [neillturner/kitchen-ansible#155]
It's not uncommon for an Ansible setup to have multiple role paths for organisational purpose, at the moment I have a bit of pre setup that copies all roles into one directory before running Kitchen tests. It would be good if this driver could support an array of roles and copy/include each directory.

**Comment by neillturner** [comment]
yes we can do that. rather that swap from a string to array in the kitchn.yml which would be a breaking change i can allow you to specify multiple paths separated by colons. I have build similar code in kitchen-puppet so easy change.

**Comment by lobsterdore** [comment]
Yep that would make sense to me, awesome.

**Comment by neillturner** [comment]
actually you can already do this using the additional_copy_path  parameter. 
just put the list of additional directories in an array on this parameter and they get copied to the roles path. 
Its just not very well documented so need to make the docs better

**Comment by lobsterdore** [comment]
Ah OK, yes this does work, it requires a bit of fiddling but I think that may be down to the slightly funky structure of my project.
