### ISSUE TITLE
Sudo executes many root commands in ansible-users directory

### ISSUE THREAD

**Issue by rafe-delphix** [neillturner/kitchen-ansible#159]
Kitchen-ansible uses 'sudo -E' to execute commands as root when the 'ansible_sudo' option is enabled, as is the default case.  This causes some commands, including some gem installations, to occur in the ansible-users directory.  For example, when running kitchen against a vagrant host as user 'vagrant', it will login as vagrant, then install gems using 'sudo -E gem install ...'.  In the absence of the '-H' switch, the home directory of the sudo process is set to '/home/vagrant' instead of '/root', causing the .gem directory to be owned by root.  This causes a problem during verify because it tries to install gems for busser as 'vagrant', but the .gem directory under /home/vagrant is not writable by anyone but root.

I think that this is a problem that arises mainly when using the 'local' connection type, which I believe runs as the currently logged in user - although setting ansible_connection=ssh doesn't seem to help.  In kitchen-vagrant, the running user is root as set by 'sudo -E'.  There must be a good reason why -E was used here, but keep in mind that the default for sudo by ansible includes the -H flag.

  http://docs.ansible.com/ansible/intro_configuration.html#sudo-flags

**Comment by neillturner** [comment]
I use sudo -E so i can pass in environment variables. 
I could add the -H parameter to the sudo so it is sudo -E -H 
or I can have a sudo_flags parameter that say defaults to -E  -H 
so folks can set it back to just -E if they have issues. 
would this work?

**Comment by rafe-delphix** [comment]
I'm beginning to think maybe the simplest course of action, adding the -H is the best approach.  I noticed that during the ruby for busser installation you are deleting /home/vagrant/.gem.  Is it possible someone ran in to something like this before or were you really intent upon deleting the cache from /home/vagrant every time?

**Comment by neillturner** [comment]
Try setting in kitchen.yml file in the provisioner section the sudo_command so it has the -H 
for example:  
  provisioner:
    sudo_command: 'sudo -E -H'

**Comment by neillturner** [comment]
now have to option to set the sudo_command to 'sudo -E -H' in version 0.42.4
