### ISSUE TITLE
No documentation for librarian-ansible integration

### ISSUE THREAD

**Issue by alexharv074** [neillturner/kitchen-ansible#161]
Looking through the code it seems to me that there is integration with librarian-ansible but how to use it does not seem to be documented.

**Comment by neillturner** [comment]
fair point i will add some to the readme. Its pretty easy all you do is add a Ansiblefile is the top level of the repository and it the same way that chef and puppet work with test-kitchen. 

there are some good links on the format of the file and how to use: 
see https://werner-dijkerman.nl/2015/08/15/using-librarian-ansible-to-install-ansible-roles-from-gitlab/
and https://github.com/bcoe/librarian-ansible.

**Comment by alexharv074** [comment]
In the end I figured out it's better to be using `requirements.yml`.

**Comment by alexharv074** [comment]
Ah and I hadn't seen the provisioning readme when I wrote this.  A bit clearer now.

**Comment by neillturner** [comment]
closing documented
