### ISSUE TITLE
Do we really need to require librarian?

### ISSUE THREAD

**Issue by alexharv074** [neillturner/kitchen-ansible#167]
Code ref [here](https://github.com/neillturner/kitchen-ansible/blob/954ecd777286197c253cd72d3ce0cbfb9e91070d/kitchen-ansible.gemspec#L34).  I think most people won't need Librarian-ansible?

**Comment by neillturner** [comment]
I will see if i can make this optional, it is how chef and puppet provisioners work.

**Comment by trumant** [comment]
I'm a +1 on this. `ansible-galaxy` support should be sufficient. I've never encountered anyone in the Ansible community continuing to use Librarion-ansible after ansible-galaxy became stable.

**Comment by neillturner** [comment]
changed in 0.44.2 so not librarian-ansible installed. 
If kitchen-ansible finds an AnsibleFile it will put out error message and people will have to install manually i.e.
 gem install librarian-ansible
