### ISSUE TITLE
sudo: /usr/local/bin/bundle: command not found using kitchen verfiy

### ISSUE THREAD

**Issue by lmeyemezu** [neillturner/kitchen-ansible#170]
Hi, 
i'm using kitchen-ansible with azurerm driver.
below is my kitchen.ym file 
 username: azure
  ssh_key: ~/.ssh/azure

provisioner:
  name: ansible_playbook
  #ansible_connection: local
  #roles_path: tests
  hosts: vm
  #requirements_path: requirements.yml
  require_ansible_repo: true
  ansible_verbose: true
  ansible_version: "2.1.0.0"
  require_ruby_for_busser: true 
  require_ansible_omnibus: true

platforms:
  - name: centos-7.1
    driver_config:
      image_urn: OpenLogic:CentOS:7.1:latest

verifier:
  name: serverspec
  sudo_path: true

suites:
  - name: default
    provisioner:
      require_ansible_repo: false
      require_ansible_source: false      
      playbook: tests/test.yml

using kitchen login and which bundle command, i get ~/bin/bundle
bundler is not installed in/usr/local/bin but in bin directory of the default user.
Regards.

**Comment by neillturner** [comment]
This really a kitchen-verifier-serverspec but i can answer. 
the answer is that you can add extra parameters under verifier: section: 
 bundler_path	'/usr/local/bin'	path for bundler command
 rspec_path	'/usr/local/bin'	path for rspec command

**Comment by lmeyemezu** [comment]
Hi,
thanks for reply.
i add bundler_path: '/opt/rh/ruby200/root/usr/local/share/gems/gems/bundler-1.12.5/exe' to kitchen.yml and it works now.
omnibus installer does not install in /usr/local/bin i presume ?

**Comment by neillturner** [comment]
i open to suggestion. I think I will change the code to just update the PATH with the bundler_path. unfortunately it can be in different locations and have not figured it all out yet. -)

**Comment by lmeyemezu** [comment]
great...
thanks

Cordialement,
Meye-Mezu Lylian
Tel.:06 98 93 13 14

2016-05-30 15:02 GMT+02:00 Neill Turner <notifications@github.com>:

**Comment by neillturner** [comment]
This is now more dynamic and it tries to figure out the location. see kitchen-verifier-serverspec 0.4.6
