### ISSUE TITLE
Kitchen won't give ansible's error message

### ISSUE THREAD

**Issue by billietl** [neillturner/kitchen-ansible#172]
When runing a failing playbook with ansible, we usually get a message that looks like this : 
> TASK [Role name : Task name] *****************************************
> fatal: [Node name]: FAILED! => {"failed": true, "msg": "Some useful information that will help you debug"}

Unofrtunately, when running such playbook through kitchen, we get a message that looks like this : 

> TASK [Role name : Task name] *********************************************
> \>\>\>\>\>\> Converge failed on instance -environment name-.
> \>\>\>\>\>\> Please see .kitchen/logs/myenv.log for more details
> \>\>\>\>\>\> ------Exception-------
> \>\>\>\>\>\> Class: Kitchen::ActionFailed
> \>\>\>\>\>\> Message: SSH command failed (unexpected response 118 (#\<Net::SSH::Packet:0x00000002cb3930 @named_elements={}, @content="veradmin'^\x00\x00\x00\x0E\x00\x00\a@: variables that are passed to the task'}) \e[0m\r\n", @position=1, @type=118>))
> \>\>\>\>\>\> ----------------------

The error message is silenced and debugging is difficult.
The given log file doesn't gives much more informations that will help me fix my playbook : 

> E, [2016-05-30T14:27:40.368182 #20053] ERROR -- myenv: ------Backtrace-------
> E, [2016-05-30T14:27:40.368191 #20053] ERROR -- myenv: /var/lib/gems/2.2.0/gems/test-kitchen-1.8.0/lib/kitchen/driver/ssh_base.rb:85:in 'rescue in converge'
> E, [2016-05-30T14:27:40.368200 #20053] ERROR -- myenv: /var/lib/gems/2.2.0/gems/test-kitchen-1.8.0/lib/kitchen/driver/ssh_base.rb:88:in 'converge'
> E, [2016-05-30T14:27:40.368208 #20053] ERROR -- myenv: /var/lib/gems/2.2.0/gems/test-kitchen-1.8.0/lib/kitchen/instance.rb:565:in 'legacy_ssh_base_converge'
> E, [2016-05-30T14:27:40.368217 #20053] ERROR -- myenv: /var/lib/gems/2.2.0/gems/test-kitchen-1.8.0/lib/kitchen/instance.rb:371:in 'block in converge_action'
> E, [2016-05-30T14:27:40.368225 #20053] ERROR -- myenv: /var/lib/gems/2.2.0/gems/test-kitchen-1.8.0/lib/kitchen/instance.rb:513:in 'call'
> E, [2016-05-30T14:27:40.368234 #20053] ERROR -- myenv: /var/lib/gems/2.2.0/gems/test-kitchen-1.8.0/lib/kitchen/instance.rb:513:in 'synchronize_or_call'
> E, [2016-05-30T14:27:40.368243 #20053] ERROR -- myenv: /var/lib/gems/2.2.0/gems/test-kitchen-1.8.0/lib/kitchen/instance.rb:478:in 'block in action'
> E, [2016-05-30T14:27:40.368251 #20053] ERROR -- myenv: /usr/lib/ruby/2.2.0/benchmark.rb:288:in 'measure'
> E, [2016-05-30T14:27:40.368265 #20053] ERROR -- myenv: /var/lib/gems/2.2.0/gems/test-kitchen-1.8.0/lib/kitchen/instance.rb:477:in 'action'
> E, [2016-05-30T14:27:40.368280 #20053] ERROR -- myenv: /var/lib/gems/2.2.0/gems/test-kitchen-1.8.0/lib/kitchen/instance.rb:369:in 'converge_action'
> E, [2016-05-30T14:27:40.368290 #20053] ERROR -- myenv: /var/lib/gems/2.2.0/gems/test-kitchen-1.8.0/lib/kitchen/instance.rb:348:in 'block in transition_to'
> E, [2016-05-30T14:27:40.368298 #20053] ERROR -- myenv: /var/lib/gems/2.2.0/gems/test-kitchen-1.8.0/lib/kitchen/instance.rb:347:in 'each'
> E, [2016-05-30T14:27:40.368307 #20053] ERROR -- myenv: /var/lib/gems/2.2.0/gems/test-kitchen-1.8.0/lib/kitchen/instance.rb:347:in 'transition_to'
> E, [2016-05-30T14:27:40.368316 #20053] ERROR -- myenv: /var/lib/gems/2.2.0/gems/test-kitchen-1.8.0/lib/kitchen/instance.rb:160:in 'verify'
> E, [2016-05-30T14:27:40.368324 #20053] ERROR -- myenv: /var/lib/gems/2.2.0/gems/test-kitchen-1.8.0/lib/kitchen/instance.rb:189:in 'block in test'
> E, [2016-05-30T14:27:40.368343 #20053] ERROR -- myenv: /usr/lib/ruby/2.2.0/benchmark.rb:288:in 'measure'
> E, [2016-05-30T14:27:40.368353 #20053] ERROR -- myenv: /var/lib/gems/2.2.0/gems/test-kitchen-1.8.0/lib/kitchen/instance.rb:185:in 'test'
> E, [2016-05-30T14:27:40.368362 #20053] ERROR -- myenv: /var/lib/gems/2.2.0/gems/test-kitchen-1.8.0/lib/kitchen/command.rb:176:in 'public_send'
> E, [2016-05-30T14:27:40.368371 #20053] ERROR -- myenv: /var/lib/gems/2.2.0/gems/test-kitchen-1.8.0/lib/kitchen/command.rb:176:in 'block (2 levels) in run_action'
> E, [2016-05-30T14:27:40.368379 #20053] ERROR -- myenv: ----------------------

PS : using test-kitchen (1.8.0), kitchen-ansible (0.42.5) and kitchen-docker (2.4.0) on ubuntu.

**Comment by neillturner** [comment]
thanks for the feedback. Generally test kitchen is pretty good at capturing logs. it also stores them in .the .kitchen directory on your workstation so you can see them. 
the log capturing is actually done by the test-kitchen core code, not the kitchen-ansible plugin but i will look into it. 
have you tried adding debug logging. ie
kitchen converge XYZ  -l debug

**Comment by billietl** [comment]
I already looked in the .kitchen directory but the logs content is pretty much what I showed in my previous message.
I tried using kitchen converge XYZ -l debug and setting ansible verbosity to 5 but no use. Verbosity is increased, but the last error message won't show up.
If you can't resolve this issue in this project, I'll be glad to report this issue to kitchen core

**Comment by neillturner** [comment]
i thought maximum ansible verbosity was 4.

**Comment by neillturner** [comment]
Well i tested it and i see the fatal errors in the test-kitchen log: 
 
 TASK [tomcat : Download Tomcat] ************************************************

 [1;30mtask path: /tmp/kitchen/roles/tomcat/tasks/main.yml:16[0m

 [0;34mESTABLISH LOCAL CONNECTION FOR USER: root[0m

 [0;34mlocalhost EXEC /bin/sh -c '( umask 22 && mkdir -p "` echo $HOME/.ansible/tmp/ansible-tmp-1464693497.24-130679269070123 `" && echo "` echo $HOME/.ansible/tmp/ansible-tmp-1464693497.24-130679269070123 `" )'[0m

 [0;34mlocalhost PUT /tmp/tmp7a6RdY TO /root/.ansible/tmp/ansible-tmp-1464693497.24-130679269070123/get_url[0m
 
 [0;34mlocalhost EXEC /bin/sh -c 'LANG=en_US.UTF-8 LC_ALL=en_US.UTF-8 LC_MESSAGES=en_US.UTF-8 /usr/bin/python /root/.ansible/tmp/ansible-tmp-1464693497.24-130679269070123/get_url; rm -rf "/root/.ansible/tmp/ansible-tmp-1464693497.24-130679269070123/" > /dev/null 2>&1'[0m

 [0;31mfatal: [localhost]: FAILED! => {"changed": false, "dest": "/opt/apache-tomcat-7.0.61.tar.gz", "failed": true, "invocation": {"module_args": {"backup": null, "checksum": "", "content": null, "delimiter": null, "dest": "/opt/apache-tomcat-7.0.61.tar.gz", "directory_mode": null, "follow": false, "force": false, "force_basic_auth": false, "group": null, "headers": null, "http_agent": "ansible-httpget", "mode": null, "owner": null, "regexp": null, "remote_src": null, "selevel": null, "serole": null, "setype": null, "seuser": null, "sha256sum": "", "src": null, "timeout": 10, "url": "http://archive.apache.org/dist/xxxxxxxtomcat/tomcat-7/v7.0.61/bin/apache-tomcat-7.0.61.tar.gz", "url_password": null, "url_username": null, "use_proxy": true, "validate_certs": true}, "module_name": "get_url"}, "msg": "Request failed", "response": "HTTP Error 404: Not Found", "state": "absent", "status_code": 404, "url": "http://archive.apache.org/dist/xxxxxxxtomcat/tomcat-7/v7.0.61/bin/apache-tomcat-7.0.61.tar.gz"}[0m
