### ISSUE TITLE
#160 (set role name in configuration) seems to have regressed

### ISSUE THREAD

**Issue by gregsymons** [neillturner/kitchen-ansible#187]
#160 made it possible to set the role name in the configuration to support the use case where the working directory does not have the same name as the role.

At some point this stopped working. I haven't figured out where for sure, but I suspect it is related to #182 and #183.

**Comment by neillturner** [comment]
do you have a test case so i can fix or just describe in a little more detail how to reproduce.

**Comment by neillturner** [comment]
if seems role_name was never defined as a parameter so I added it.

**Comment by gregsymons** [comment]
I mostly opened this in case someone else fixed it before I got around to it :) I'm not 100% sure your fix will solve the problem, but I'll update to the new version and check. If it doesn't, I'll post a more complete test case, or, if I have time, fix it and open a PR.
