### ISSUE TITLE
apt-get update before installing packages?

### ISSUE THREAD

**Issue by farrellit** [neillturner/kitchen-ansible#19]
Currently the opscode-ubuntu-14,04 vagrant boxes we've been using at work appear to ship with out of date apt repository metadata.  

<pre>
The following NEW packages will be installed:
  python3-pycurl python3-software-properties software-properties-common
0 upgraded, 3 newly installed, 0 to remove and 0 not upgraded.
Need to get 76.0 kB of archives.
After this operation, 542 kB of additional disk space will be used.
Get:1 http://us.archive.ubuntu.com/ubuntu/ trusty/main python3-pycurl amd64 7.19.3-0ubuntu3 [47.5 kB]
Err http://us.archive.ubuntu.com/ubuntu/ trusty-updates/main python3-software-properties all 0.92.37.1
  404  Not Found [IP: 91.189.91.24 80]
Err http://us.archive.ubuntu.com/ubuntu/ trusty-updates/main software-properties-common all 0.92.37.1
  404  Not Found [IP: 91.189.91.24 80]
Fetched 47.5 kB in 5s (8,997 B/s)
E: Failed to fetch http://us.archive.ubuntu.com/ubuntu/pool/main/s/software-properties/python3-software-properties_0.92.37.1_all.deb  404  Not Found [IP: 91.189.91.24 80]

E: Failed to fetch http://us.archive.ubuntu.com/ubuntu/pool/main/s/software-properties/software-properties-common_0.92.37.1_all.deb  404  Not Found [IP: 91.189.91.24 80]

E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
</pre>

Then the `apt-add-repository` command fails, the ansible repo isn't added and I end up with ansible 1.5.4.  

Wouldn't it be logical to run an apt-get update _before_ we try to start installing packages? If I do an update first, all the commands appear to succeed.

**Comment by farrellit** [comment]
I think that would be nice.  My issue is that I've already started distributing kitchen.yml files between the developers, and when the opscode images fall behind, it's hard to update those kitchen.yml files to point to a locally maintained box ... thought that's probably the right solution for me anyway, the apt-get update optionally running before any installs would effectively solve the problem.  In my experience, it's not too unusual for vbox boxes to be out of date with the current apt repositories.  Thanks for looking at my issue!

**Comment by neillturner** [comment]
feel free to mod code and send pull request. the code is pretty straight forward i think. if you have problem then i can code it for you.

**Comment by trinitronx** [comment]
@jolexa:  :+1:  on this PR.   I've had experience with various bento boxes not having up-to-date repo cache (whether `apt-get` or `yum` based).  Running `apt-get update` or `yum makecache` first should help alleviate this with stale repo caches.

**Comment by jolexa** [comment]
@trinitronx BTW, this issue can be closed :)
