### ISSUE TITLE
Race condition causes ansible omnibus / pip install to fail if ubuntu cloud-init is still running

### ISSUE THREAD

**Issue by MTN-RowinAndruscavage** [neillturner/kitchen-ansible#192]
Hello!  Just wanted to report an issue I encountered trying to launch Ubuntu 14.04 test kitchen instances in AWS EC2 from a Jenkins instance also in EC2.  The `apt-get update` command and subsequent `apt-get install python-pip ...` commands appear to fail if they run before the ubuntu cloud-init script finishes its thing.  Could not repro this running kitchen from my local machine, I suppose because the extra network hops add just enough delay to let cloud-init finish.  

We were seeing errors during the ansible omnibus and pip install section like:
       ```
       Package python-httplib2 is not available, but is referred to by another package.
       This may mean that the package is missing, has been obsoleted, or
       is only available from another source
       
       Package python-paramiko is not available, but is referred to by another package.
       This may mean that the package is missing, has been obsoleted, or
       is only available from another source
       
       Package python-jinja2 is not available, but is referred to by another package.
       This may mean that the package is missing, has been obsoleted, or
       is only available from another source
       
       E: Unable to locate package python-pip
       E: Package 'python-jinja2' has no installation candidate
       E: Package 'python-httplib2' has no installation candidate
       E: Package 'python-paramiko' has no installation candidate
       E: Unable to correct problems, you have held broken packages.
       /tmp/ansible_install.sh: 76: [: Reading: unexpected operator
       ```

with kitchen-ansible finally failing out with `/bin/bash: ansible-playbook: command not found`

I was able to get kitchen jobs working consistently from Jenkins by adding a "wait_for_cloud_init" routine by tweaking the ansible omnibus install script as shown in
https://gist.github.com/MTN-RowinAndruscavage/139af7b2afcff4cff09a44b2efc40ef4

and using `ansible_omnibus_url: https://gist.github.com/MTN-RowinAndruscavage/139af7b2afcff4cff09a44b2efc40ef4/raw/64ac9f5acbba197012acfd921154bf32b1bbe9a6/ansible_install.sh`

(also scattered a bunch of `-q` around the apt-get and pip commands to make the output more Jenkins-friendly)

Thanks for the cool test automation tools, this really makes our work so much more pleasant!

**Comment by neillturner** [comment]
that nice you could workaround issue by creating modified ansible_install.sh and pointing ansible_omnibus_url parameter to it.
Would you like me to update omnibus_ansible? are you changes generic so they work ok if other are running the script in our environments?

**Comment by MTN-RowinAndruscavage** [comment]
Yes, I think this should help out others who may run into this issue, which was a bit frustrating to diagnose.  And we would certainly prefer tracking your upstream omnibus ansible_install.sh instead of maintaining our own little fork.

There's probably a better way to check that cloud-init has completed other than the pgrep command I'm using, but it should be pretty harmless on other systems.

**Comment by neillturner** [comment]
I pushed this change to omnibus-ansible so closing. 
this is the commit: 
https://github.com/neillturner/omnibus-ansible/commit/ff0ffd31b215ef3dfbac85fbfb47cb3b5874fd83
