### ISSUE TITLE
executable ansible_vault_password_file

### ISSUE THREAD

**Issue by hryamzik** [neillturner/kitchen-ansible#200]
ansible_vault_password_file is just copied to the test VM but it might not work there. For example my executable takes vault password from a kaychain found by git remote url.

**Comment by neillturner** [comment]
What would you like a parameter to set the permissions of the file so it can b executable?

**Comment by hryamzik** [comment]
Let's say a `ansible_vault_password_extract` option to execute script on a host system and put it's output to a target VM.

**Comment by neillturner** [comment]
you need to explain a bit more. usually people right the code and create pull requests. the code is quite simple really.

**Comment by hryamzik** [comment]
With this option enabled vault script has to be executed on a host system, output collected and put to a text vault file on a test VM.

**Comment by neillturner** [comment]
closing as he is going to use ansiblepush
