### ISSUE TITLE
non-localhost provsions

### ISSUE THREAD

**Issue by hryamzik** [neillturner/kitchen-ansible#201]
Is it possible to use non-localhost hosts for tests and run ansible from the source machine? There're several reasons for that:

- testing multi-host deployments
- running playbooks that require files from operator's machine
- accessing other hosts that are not part of test environment
- vault related issues like #200

**Comment by neillturner** [comment]
Yes ansible can be run in ssh mode to handle these cases if you need some extra parameters or features log an issue or even better write a pull request

**Comment by hryamzik** [comment]
Thanks, I'll fire a feature request.
