### ISSUE TITLE
Feature request: ssh mode

### ISSUE THREAD

**Issue by hryamzik** [neillturner/kitchen-ansible#202]
Let me request an ssh-mode model. Here're the goals:
- run playbooks from the original host as they may include calls to some local resources and environment variables
- test playbooks against a group of hosts that relay on each others facts
- test playbooks that rely on inventory and host/group vars from real hosts

As mixing real inventory with vagrant one may be tricky let me notice that it could be done with [ansible-vagrant-inventory](/gitinsky/ansible-vagrant-inventory).

Based on #201

**Comment by neillturner** [comment]
ssh mode is already supported

**Comment by hryamzik** [comment]
But can I avoid copying files and just run ansible with kitchen right in the project folder?

**Comment by neillturner** [comment]
well if you want to run ansible on your workstation try the ansiblepush plugin. 
my plugin always create  another server installs ansible and copies the project. then you can have another set of servers that you use ssh on. 
the kitchen-verifier-serverspec plugin that i wrote allows you to run serverspec natively on your workstation so combining that with ansiblepush might do what you want.

**Comment by hryamzik** [comment]
Thanks, looks like [ansiblepush](/ahelal/kitchen-ansiblepush) does exactly what I'm looking for!
