### ISSUE TITLE
Issue with custom filter

### ISSUE THREAD

**Issue by awiddersheim** [neillturner/kitchen-ansible#209]
I have a custom filter for one of my roles. Seems that since Ansible runs as root the filter's .pyc gets root ownership making it impossible to copy over after the initial run. Not sure how best to approach this problem.

```
[vagrant@default-centos-7 filter_plugins]$ ls -la
total 12
drwxr-xr-x. 2 vagrant vagrant   41 Oct 15 23:17 .
drwxr-xr-x. 8 vagrant vagrant 4096 Oct 15 23:17 ..
-rw-r--r--. 1 vagrant vagrant  358 Oct 16 12:35 filters.py
-rw-r--r--. 1 root    root     886 Oct 15 23:17 filters.pyc
```

```
       Transferring files to <default-centos-7>
D      TIMING: scp async upload (Kitchen::Transport::Ssh)
D      Cleaning up local sandbox in /var/folders/qc/6g026c3x04n4f6xyhlb_k_70xhsw08/T/default-centos-7-sandbox-20161016-12666-1m1q0bz
D      DONE!!!
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ActionFailed
>>>>>> Message: 1 actions failed.
>>>>>>     Failed to complete #converge action: [scp: /tmp/kitchen/bootstrap/filter_plugins/filters.pyc: Permission denied
] on default-centos-7
>>>>>> ----------------------
>>>>>> Please see .kitchen/logs/kitchen.log for more details
>>>>>> Also try running `kitchen diagnose --all` for configuration
```

**Comment by awiddersheim** [comment]
Seems I would need something slightly similar to `ignore_paths_from_root` but an `ignore_file_extensions` so `*.pyc` files don't get copied.

**Comment by neillturner** [comment]
we can have an ignore_file_extensions parameter which is an array of file extensions
i think we just need in the prepare_additional_copy_path method before
 FileUtils.cp(file, destination)
the following
    config[:ignore_file_extensions].each do |ext|
        next if File.extname(source) == ext
    end

**Comment by awiddersheim** [comment]
I dug into this a bit and noticed my failure seemed to be happening from inside Test-Kitchen code. Right around here:

https://github.com/test-kitchen/test-kitchen/blob/8be7ca20886717f35bc7baf11340a86a48b2a28b/lib/kitchen/driver/ssh_base.rb#L302

Does the `prepare_additional_copy_path` method control what files Test-Kitchen is sending?

**Comment by neillturner** [comment]
the kitchen-ansible plugin create a sandbox and the prepare_additional_copy_path controls what additional files go into the sandbox. the the test-kitchen core code copies the sandbox files to the remote server typically via ssh.

**Comment by awiddersheim** [comment]
Right, this is where my confusion is. Here is a quick look at my role's directory structure locally:

```
├── defaults
├── filter_plugins
│   ├── filters.py
│   └── filters.pyc
├── tasks
├── templates
└── test
```

When I run `kitchen converge` I get that could not copy error. This is because in the kitchen VM the permissions are like so:

```
[root@default-centos-7 ~]# ls -lha /tmp/kitchen/myrole/filter_plugins/
total 12K
drwxr-xr-x. 2 vagrant vagrant   41 Oct 17 17:46 .
drwxr-xr-x. 8 vagrant vagrant 4.0K Oct 16 22:18 ..
-rw-r--r--. 1 vagrant vagrant  358 Oct 17 17:46 filters.py
-rw-r--r--  1 root    root     886 Oct 17 17:46 filters.pyc
```

This is because I tell Ansible to run as root and Python compiles my filter but the copy must happen as vagrant.

Locally, if I remove `filters.pyc` and run `kitchen converge` again, everything works fine. It seems like Test-Kitchen is what is responsible for copying my role over. Not the Kitchen-Ansible provisioner plugin.

Not sure how to tie into that and tell it to ignore `*.pyc` files.

**Comment by neillturner** [comment]
if you run with -l debug you will see more log messages that will help explain. 
 i suggest you put the code 
   next if File.extname(source) == 'pyc' 
 in the prepare_additional_copy_path method before
   FileUtils.cp(file, destination)
and see if that works, 
 you will find the code in the file ansible_playbook.rb
in directory whwn ruby is installed 
 \ruby\gems\2.1.0\gems\kitchen-ansible-0.45.5\lib\kitchen\provisioner

**Comment by awiddersheim** [comment]
I made this change and still continue to get the same error.

**Comment by awiddersheim** [comment]
Ah! Think I got it. Will work on patch. Much appreciated.
