### ISSUE TITLE
Incorrect OS detection for Amazon Linux

### ISSUE THREAD

**Issue by mjulian** [neillturner/kitchen-ansible#216]
The OS detection for Amazon Linux doesn't work on 2016.03 due to it not having `/etc/centos-release` and `/etc/redhat-release`, though it does have `/etc/system-release`. As a result, it falls back to the final `else` clause (install via apt, which is probably the wrong failure mode for this--bailing with an error is probably a better approach). End result of all this is that Amazon support is broken.

**Comment by neillturner** [comment]
how should we detect it then?

**Comment by mjulian** [comment]
I would break it out of the RH conditional (giving it it's own conditional) and then grep `/etc/issue` for the string `Amazon`.

**Comment by neillturner** [comment]
fixed in version 0.45.6
