### ISSUE TITLE
Unable to create local directories(/home/vagrant/.ansible/tmp): [Errno 13] Permission denied

### ISSUE THREAD

**Issue by wasimkham** [neillturner/kitchen-ansible#218]
I'm trying to use an Ansible Galaxy package with test kitchen. I've put the following into a `requirements.yml` file in the root directory:

```
---
# Install a role from the Ansible Galaxy
- src: geerlingguy.mysql
```

Then in `kitchen.yml`

```
provisioner:
  name: ansible_playbook
  roles_path: roles
  hosts: dev
  require_ansible_repo: true
  ansible_verbose: true
  ansible_version: latest
  ansible_vault_password_file: .vault_pass
  group_vars_path: group_vars_dev
  requirements_path: requirements.yml
```

But it fails, complaining about not being able to create a local directory.

```
D      [SSH] vagrant@127.0.0.1<{:user_known_hosts_file=>"/dev/null", :paranoid=>false, :port=>"2201", :compression=>false, :compression_level=>0, :keepalive=>true, :keepalive_interval=>60, :timeout=>15, :keys_only=>true, :keys=>["/Users/username/Sites/ansible/.kitchen/kitchen-vagrant/kitchen-db-ubuntu-1604/.vagrant-laptop/machines/default/virtualbox/private_key"], :auth_methods=>["publickey"], :user=>"vagrant"}> (sudo -E sh -c '[ -d /etc/ansible ] || mkdir /etc/ansible' && sudo -E cp /tmp/kitchen/ansible.cfg /etc/ansible && sudo -E cp -r /tmp/kitchen/group_vars /etc/ansible/. && sudo -E cp -r /tmp/kitchen/host_vars /etc/ansible/. && ansible-galaxy install --force -p /tmp/kitchen/roles -r /tmp/kitchen/requirements.yml)
       Traceback (most recent call last):
         File "/usr/bin/ansible-galaxy", line 43, in <module>
           import ansible.constants as C
         File "/usr/lib/python2.7/dist-packages/ansible/constants.py", line 161, in <module>
           DEFAULT_LOCAL_TMP         = get_config(p, DEFAULTS, 'local_tmp',        'ANSIBLE_LOCAL_TEMP',      '$HOME/.ansible/tmp', istmppath=True)
         File "/usr/lib/python2.7/dist-packages/ansible/constants.py", line 81, in get_config
           makedirs_safe(value, 0o700)
         File "/usr/lib/python2.7/dist-packages/ansible/utils/path.py", line 67, in makedirs_safe
           raise AnsibleError("Unable to create local directories(%s): %s" % (to_native(rpath), to_native(e)))
       ansible.errors.AnsibleError: Unable to create local directories(/home/vagrant/.ansible/tmp): [Errno 13] Permission denied: '/home/vagrant/.ansible/tmp'
D      Cleaning up local sandbox in /var/folders/80/7z_l0ck13lq175wz0f38h0f40000gn/T/db-ubuntu-1604-sandbox-20161213-3994-1yq02lh
```

Any ideas?

**Comment by neillturner** [comment]
Well if it can't create the directory then the user that test-kitchen is logging on vagrant with doesn't have the permission. I would try using root instead of the vagrant user or set the sudo option.

**Comment by neillturner** [comment]
closing this as no more activity. will re-open if i get anymore activity.

**Comment by ferrarimarco** [comment]
@neillturner Hi, I have the very same issue.

You can see the details in the dev branch of my role: https://github.com/ferrarimarco/ansible-role-eclipse/tree/development

On Travis I don't have this issue, so it's dependent on my environment.

thanks

**Comment by neillturner** [comment]
permission can be an issue. it depends if the command creating the file runs as sudo and then later the command to read the file is not sudo then these sort of issue happen.  When i get time i have a bit of a test.

**Comment by ferrarimarco** [comment]
@neillturner is there any update? Thanks!

**Comment by neillturner** [comment]
If you have .kitchen.yml file that uses vagrant (and include the virtual box image name) to reproduce the problem that i can use to reproduce then that would be great as i can then reproduce and fix.

**Comment by ferrarimarco** [comment]
I don't currently have one (I am searching for a relevant Travis failing build). I'll let you know when I find one...

**Comment by ferrarimarco** [comment]
@neillturner Hi!

Here is a .kitchen.yml that produces the issue:
```

---
driver:
  name: vagrant

platforms:
  - name: ubuntu-16.04

provisioner:
  ansible_connection: local
  ansible_host_key_checking: false
  ansible_version: 2.2.1.0
  name: ansible_playbook
  hosts: test-kitchen
  idempotency_test: true
  require_ansible_repo: false
  require_chef_for_busser: false
  require_ruby_for_busser: false
  require_pip: true
  requirements_path: requirements.yml
  role_name: ferrarimarco.docker
  roles_path: .

suites:
  - name: default

verifier:
  name: inspec
```

**Comment by ferrarimarco** [comment]
@neillturner hi, is there an update on this? Thanks!

**Comment by ferrarimarco** [comment]
Here is a temporary workaround, to add in your `.kitchen.yml` file in the `provisioner` section: `custom_pre_play_command: chown -R  kitchen:kitchen /home/kitchen/.ansible`

Example:
```
provisioner:
  custom_pre_play_command: chown -R  kitchen:kitchen /home/kitchen/.ansible
```

**Comment by trinitronx** [comment]
Seems like this issue could also be worked around by setting either `ansible.cfg` setting: [`remote_tmp`](http://docs.ansible.com/ansible/intro_configuration.html#remote-tmp) or [`local_tmp`](http://docs.ansible.com/ansible/intro_configuration.html#local-tmp)

`local_tmp` will only work for Ansible >= 2.1 as it is a newer config option.

**Comment by neillturner** [comment]
I'm closing this. Nor much i can do about permission issues. it depends on the user that is used to logon via ssh and the particular ssh options depended on the server.

**Comment by ferrarimarco** [comment]
@neillturner can't you set `kitchen:kitchen` as the owner of `.ansible` when you create that directory?

**Comment by neillturner** [comment]
good idea i will make an option  dot_ansible_path_owner that defaults to empty
 but a comment to set  it to 'kitchen:kitchen'. 

we could have another parameter for the .ssh as well dot_ssh_path_owner?

**Comment by ferrarimarco** [comment]
Could be useful! Thx @neillturner

**Comment by neillturner** [comment]
as there is a workaround: 
```
provisioner:
  custom_pre_play_command: chown -R kitchen:kitchen /home/kitchen/.ansible
```
I'm closing
