### ISSUE TITLE
Private Git Repo in requirements.yml does not work without private ssh key

### ISSUE THREAD

**Issue by emoshaya-cognito** [neillturner/kitchen-ansible#226]
because I use private git repositories in my requirements.yml, I need to be able to upload my local ~/.ssh/id_rsa to the target host ~/.ssh/id_rsa... is there a way to do that in the provisioner?

**Comment by neillturner** [comment]
1. you need to put the /id_rsa  in the ansible repo somewhere so it get copied to the server. 
you could look at the additional_copy_path parameter 

2. then we need to add similar functionalu to the custom_pre_apply_command as in kitchen-puppet 
from https://github.com/neillturner/kitchen-puppet/blob/master/provisioner_options.md
 Try creating a pull request. I might get to on the weekend to implement.

3. then this  custom_pre_playbook_command we would put the command tomove the id_rsa file from the ansible repo on the ~/.ssh directory

**Comment by neillturner** [comment]
added custom_pre_play_command option to 0.46.1 so should be able to implement this.

**Comment by emoshaya-cognito** [comment]
Hi @neillturner  The change in 0.46.1 kind of broke the idempotency test in kitchen. I get to the end of the first converge where it is about to run the second converge to verify idempotency and I get the following errors: 
bash: -c: line 3: syntax error near unexpected token `&&'
bash: -c: line 3: ` && (echo 'going to invoke ansible-playbook second time:';

**Comment by neillturner** [comment]
thanks for letting me  i will fix -)

**Comment by neillturner** [comment]
fixed in 0.46.2 but i will still add an option  ssh_private_keys

**Comment by emoshaya-cognito** [comment]
thanks @neillturner any update on the ssh_private_keys option?

**Comment by neillturner** [comment]
additional_ssh_private_keys parameter in version 0.46.3
would be great if you can test.
