### ISSUE TITLE
Old ansible version 1.7.2 installed on Debian Jessie platform

### ISSUE THREAD

**Issue by AlexeyDemidov** [neillturner/kitchen-ansible#228]
With platform: `debian-8.7` `add-apt-repository ppa:ansible/ansible` command adds following line to the apt sources:

`deb http://ppa.launchpad.net/ansible/ansible/ubuntu jessie main`

Notice 'jessie' as release name, while 'trusty' is required to install 'ansible' on the Debian platform. 
This line results in 404 error during `apt-get update`

`W: Failed to fetch http://ppa.launchpad.net/ansible/ansible/ubuntu/dists/jessie/main/binary-amd64/Packages  404  Not Found`

And as a result you get outdated `ansible` version 1.7.2 installed.

**Comment by neillturner** [comment]
can't see where that is the code, should be in lib/kitchen/provisioner/ansible/os/debian.rb. 
I just do a add-apt-repository ppa:ansible/ansible
is this a bug in ansible setup on debian???
do you have output from a test-kitchen run with -l debug.
is there a vagrant images somewhere with debian-8.7.

**Comment by AlexeyDemidov** [comment]
The code, as you said, in the lib/kitchen/provisioner/ansible/os/debian.rb, call to 'add-apt-repository' on the [line 59](https://github.com/neillturner/kitchen-ansible/blob/master/lib/kitchen/provisioner/ansible/os/debian.rb#L59) But it doesn't work as you expect it to - it adds repo with release name 'jessie' but you need 'trusty' to install ansible on Debian. I don't see in the 'add-apt-repostory' man page how to change release name added. 

You can find Vagrant image for Debian 8.7 on Atlas  https://atlas.hashicorp.com/bento/boxes/debian-8.7/ , but adding 'platform: debian-8.7' to the .kitchen.yml will retrieve this image automatically.

**Comment by neillturner** [comment]
I guess the workaround is to use one of the other ansible install options documented in: 
https://github.com/neillturner/kitchen-ansible/blob/master/provisioner_options.md

**Comment by neillturner** [comment]
try in .kitchen.yml setting 
ansible_apt_repo:  ppa:ansible/ansible-2.1

**Comment by AlexeyDemidov** [comment]
I'm already using ppa for 2.1 as workaround for issue #227 but it still adds incorrect repository. I have to manually change 'jessie' to 'trusty' in source.list every time I build Vagant VM. I'll try omnibus installer with version set to 2.1.5.0. Documentation seems to be incorrect about that `ansible_version` in .kitchen.yml affects only `apt-get` installs.

**Comment by neillturner** [comment]
Not sure what i can do to fix this. Seems to be a problem with the packaging of ansible on debian based systems. When i get  a bit of time i will try and investigate how ansible should be installed on debian based systems.

**Comment by neillturner** [comment]
ok what i can do is test for debian in /etc/lsb-release
and then instead of 
   add-apt-repository ppa:ansible/ansible
i do 
   echo "deb http://ppa.launchpad.net/ansible/ansible/ubuntu trusty main" > /etc/apt/sources.list 
   apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 93C4A3FD7BB9C367
where trusty will be the DISTRIB_CODENAME from the /etc/ls-release 
 cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=14.04
DISTRIB_CODENAME=trusty
DISTRIB_DESCRIPTION="Ubuntu 14.04 LTS"

**Comment by AlexeyDemidov** [comment]
/etc/lsb-release doesn't exist on Debian. You can check for /etc/os-release which contains something like this:

PRETTY_NAME="Debian GNU/Linux 8 (jessie)"
NAME="Debian GNU/Linux"
VERSION_ID="8"
VERSION="8 (jessie)"
ID=debian
HOME_URL="http://www.debian.org/"
SUPPORT_URL="http://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"

**Comment by AlexeyDemidov** [comment]
According to [Ansible Installation Page](http://docs.ansible.com/ansible/intro_installation.html#latest-releases-via-apt-debian) you can use `trusty` on Debian Jessie and Stretch.

**Comment by neillturner** [comment]
fixed in version 0.46.4
