### ISSUE TITLE
Installation of Ansible fails on Ubuntu 13.04

### ISSUE THREAD

**Issue by metmajer** [neillturner/kitchen-ansible#23]
I have just observed the following error when converging a Ubuntu 13.04 box provided from Opscode:

````
WARNING: The following packages cannot be authenticated!

 python-jinja2 ansible python-pkg-resources
E: There are problems and -y was used without --force-yes
```

The box's name is ```opscode-ubuntu-13.04```, taken from [https://opscode-vm-bento.s3.amazonaws.com/vagrant/virtualbox/opscode_ubuntu-13.04_chef-provisionerless.box](https://opscode-vm-bento.s3.amazonaws.com/vagrant/virtualbox/opscode_ubuntu-13.04_chef-provisionerless.box).

Best, Martin

**Comment by trinitronx** [comment]
This seems like an issue with the packages not being signed, or missing apt-key?

I think I ran into similar repo issues on some of the [End of Life versions of Ubuntu][1].  I've not had time to dedicate towards supporting all of the [bento box][2] platforms.  That test matrix is massively daunting! 

I've noticed that #17 has changed from using the [rquillio/ansible PPA][3] to the more official [ansible/ansible PPA][4] which only supports these versions of Ubuntu currently:

    Trusty (14.04)
    Saucy (13.10)
    Precise (12.04)
    Lucid (10.04)

One idea is probably try using the old repo via this workaround in your `.kitchen.yml`:

    provisioner:
      name: ansible_playbook
      require_ansible_repo: true
      ansible_apt_repo: ppa:rquillo/ansible


[1]: http://askubuntu.com/questions/382579/where-i-can-find-the-status-of-the-released-versions-of-ubuntu
[2]: https://github.com/chef/bento
[3]: https://launchpad.net/~rquillo/+archive/ubuntu/ansible
[4]: https://launchpad.net/~ansible/+archive/ubuntu/ansible

**Comment by metmajer** [comment]
Why don't we do something like:

```
apt-get install -y build-essential python-dev python-setuptools
cd /tmp && wget http://releases.ansible.com/ansible/ansible-latest.tar.gz
tar xzf ansible-latest.tar.gz
cd ansible-* && python setup.py install
````

**Comment by trinitronx** [comment]
I had thought of trying something like this but still need a basic way to get it to work cross-distro or `platform_family`.  Had been short on time to get something tested and working on all platforms.  I suppose a start would be Ubuntu & RHEL/CentOS/Fedora.

**Comment by trinitronx** [comment]
Also it's not clear what the official and dependable way to install Ansible is: pip or something like you posted.  Ideally we'd want it to be reliable and fast to install.  I've had bad luck with random source tarball URLs changing on me so that's why I'm hesitant.

**Comment by metmajer** [comment]
Understood. However, the URL presented above is a working URL. I have been using this snippet in our own orchestration layer and we have not had any issues with its availability so far. What do you think?

**Comment by trinitronx** [comment]
Well I guess the only way to find out is to try it.  Perhaps we can create a script that does some basic platform detection and use the tarball method as the "omnibus" & latest install script for Ansible since that somewhat mirrors Test-kitchen's omnibus install capability for Chef.

That way we'd have a couple methods to install it that we allow people to use that as a fall back method if necessary, and keep the behavior similar to using test-kitchen with Chef so people know what to expect.

**Comment by neillturner** [comment]
As long as things are configurable and documented i'm easy. It seemed sensible to set the default to the official ansible PPA. We could add additional parameters say: 
  require_ansible_release: true
  ansible_release: latest
that could then use the script from metmajer. 
If you guy like this then create a pull request or i can write it based on metmajer's script if you insist. -)
It should be relatively easy to create the script for redhat based systems.

**Comment by neillturner** [comment]
I believe ubuntu-13.04 works if 
     ansible_apt_repo: ppa:rquillo/ansible
is set in the .kitchen.yml
