### ISSUE TITLE
how do I access copied ssh keys

### ISSUE THREAD

**Issue by jamesla** [neillturner/kitchen-ansible#230]
I require a key on my box to download the prerequisite galaxy roles.

I have copied the key (id_rsa) using the additional_ssh_private_keys key and which works successfuly and copies it to ~/.ssh/ssh_private_keys/id_rsa

How can I tell kitchen-ansible to this key by default or when downloading Ansible roles (via ansible-galaxy)?

**Comment by neillturner** [comment]
from what i can see you can't specify this in requirements.yml. 
If you call the ssh key 
~/.ssh/id_rsa
this it will be used by default 
otherwise i guess we will need a 
~/.ssh/config
like: 
host github.com
 HostName github.com
 IdentityFile ~/.ssh/id_rsa_github
 User git
that connects the host name to the ssh key.

**Comment by jamesla** [comment]
Thanks Neil, that makes sense but how would I provision the test box with an ssh config in a way that it would survive a kitchen destroy; kitchen create?

**Comment by neillturner** [comment]
that would need to be an enhancement to kitchen-ansible. 
the easiest way would be to create and option 
 ssh_config
and have the config file in the kitchen.yml  much like the 
hiera_writer_files option
in kitchen-puppet https://github.com/neillturner/kitchen-puppet
  hiera_writer_files:
    - datacenter/vagrant.yaml:
      logstash_servers: []
      hosts:
        10.1.2.3:
        - puppet
        - puppetdb
so 
  ssh_config:
    host github.com
   HostName github.com
   IdentityFile ~/.ssh/id_rsa_github
   User git

**Comment by jamesla** [comment]
Ok thanks Neil. In the end I changed back to the virtual box provider so I could just use ssh key forwarding.
