### ISSUE TITLE
issues running provisioner when fish is default shell

### ISSUE THREAD

**Issue by jamesla** [neillturner/kitchen-ansible#232]
When I run kitchen converge on a box which has fish set as the default shell I get the following error as fish doesn't support && and instead uses ;

I have tried using the shell_command option to point it back at bash but it doesn't appear to do anything? Even if I make it gibberish it doesn't cause an error to be thrown.

How can I make this provisioner work when fish is the default shell on the box being provisioned?

```
       Preparing lookup_plugins
       nothing to do for lookup_plugins
       Preparing additional_ssh_private_keys
       nothing to do for additional_ssh_private_keys
       Finished Preparing files for transfer
       Installing ansible, will try to determine platform os
       Unsupported use of '&&'. In fish, please use 'COMMAND; and COMMAND'.
       fish:               elif [ -f /etc/system-release ] && [ `grep -q 'Amazon Linux' /etc/system-release` ]; then

```

**Comment by neillturner** [comment]
well you can enhance kitchen-ansible by creating a new parameter say 
 shell
that defaults to say bash. 
 then when you set the parameter to fish you can write code to change the &&  to whatever fish requires. 
I think there are about a dozen or so places in the code. 
 beware the && is also used in the ruby code.

**Comment by jamesla** [comment]
or even easier could just specify that commands are run with bash no matter the default shell using bash -c

I will have an attempt at this and send through a pull request

**Comment by neillturner** [comment]
there is a parameter  shell_command you could try setting it to bash and see if you work. 
it might need a little enhancement for your use case.
