### ISSUE TITLE
Disable output for pip install

### ISSUE THREAD

**Issue by mikef-nl** [neillturner/kitchen-ansible#235]
Hi Neill,
When using the require_pip variable the entire installation is outputted to the console. It would be useful to have an additional option to still use require_pip but send output to /dev/null (in Centos' case). It would just make the build logs when using a CI a little less complex.

**Comment by neillturner** [comment]
we could sent it to /dev/null  unless the logging is set to debug level

**Comment by mikef-nl** [comment]
I like that idea, really the only time you'll want to see all that is if something goes wrong. Just an extra config variable and then a check for it to decide on outputting to console or not.

**Comment by neillturner** [comment]
yes that would ok.
another possibility is that test-kitchen has the debug method that is called when you add -l debug to the kitchen converge command 
you would have to add the output for the pip install  to a ruby variable like pip_output and then do a debug pip_output
 to write out the output.

**Comment by mikef-nl** [comment]
True that sounds the the better option.

**Comment by mikef-nl** [comment]
Hi Neil, I have added the code necessary on a local clone of the repo. How can I get a pull request through?

**Comment by neillturner** [comment]
there should be a button create pull request if you are working off a fork of my kitchen-ansible repo

**Comment by neillturner** [comment]
Thank you in PR -  Added output to /dev/null when debug is not set #242
