### ISSUE TITLE
Ansible requirements installation is not idempotent

### ISSUE THREAD

**Issue by walterdolce** [neillturner/kitchen-ansible#241]
Hi,

Looks like the provisioner installs roles every time one converges when the requirement is defined as being pulled from Ansible Galaxy. Please see below.

Output during converge:
```
       Transferring files to <suite-name>
       - extracting logrotate to /tmp/kitchen/roles/logrotate
       - logrotate (v0.1.2) was installed successfully
       - downloading role 'php', owned by geerlingguy
       - downloading role from https://github.com/geerlingguy/ansible-role-php/archive/3.4.4.tar.gz
```

Requirements YAML file:
```
---
- name: logrotate
  src: https://github.com/debops/ansible-logrotate
  version: v0.1.2
- name: php
  src: geerlingguy.php
  version: 3.4.4
```

As you can see `logrotate` and `php` are defined differently. The former targets GitHub directly, the latter Ansible Galaxy.

Thank you.

**Comment by walterdolce** [comment]
@neillturner I see. Thank you for clarifying. I will raise this with Ansible and reference this there.

**Comment by neillturner** [comment]
closing as i don't think any kitchen-ansible code change needs fixing.
