### ISSUE TITLE
additional_copy_role_path parent folder

### ISSUE THREAD

**Issue by mikef-nl** [neillturner/kitchen-ansible#244]
When declaring additional_copy_role_path: ../ test-kitchen fails with : 
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ActionFailed
>>>>>> Message: 1 actions failed.
>>>>>>     Failed to complete #converge action: [undefined method `each' for nil:NilClass] on default-ansibleserver
>>>>>> ----------------------
>>>>>> Please see .kitchen/logs/kitchen.log for more details
>>>>>> Also try running `kitchen diagnose --all` for configuration

D      ------Exception-------
D      Class: Kitchen::ActionFailed
D      Message: 1 actions failed.
>>>>>>     Failed to complete #converge action: [undefined method `each' for nil:NilClass] on default-ansibleserver
D      ----------------------
D      ------Backtrace-------
D      C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/test-kitchen-1.16.0/lib/kitchen/command.rb:183:in `report_errors'
D      C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/test-kitchen-1.16.0/lib/kitchen/command.rb:174:in `run_action'
D      C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/test-kitchen-1.16.0/lib/kitchen/command/action.rb:36:in `block in call'
D      C:/Ruby23-x64/lib/ruby/2.3.0/benchmark.rb:293:in `measure'
D      C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/test-kitchen-1.16.0/lib/kitchen/command/action.rb:34:in `call'
D      C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/test-kitchen-1.16.0/lib/kitchen/cli.rb:53:in `perform'
D      C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/test-kitchen-1.16.0/lib/kitchen/cli.rb:187:in `block (2 levels) in <class:CLI>'
D      C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
D      C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
D      C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/test-kitchen-1.16.0/lib/kitchen/cli.rb:334:in `invoke_task'
D      C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
D      C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
D      C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/test-kitchen-1.16.0/bin/kitchen:13:in `block in <top (required)>'
D      C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/test-kitchen-1.16.0/lib/kitchen/errors.rb:171:in `with_friendly_errors'
D      C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/test-kitchen-1.16.0/bin/kitchen:13:in `<top (required)>'
D      C:/Ruby23-x64/bin/kitchen:22:in `load'
D      C:/Ruby23-x64/bin/kitchen:22:in `<main>'
D      ----End Backtrace-----
D      -Composite Exception--
D      Class: Kitchen::ActionFailed
D      Message: Failed to complete #converge action: [undefined method `each' for nil:NilClass] on default-ansibleserver
D      ----------------------
D      ------Backtrace-------
D      C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/kitchen-ansible-0.46.4/lib/kitchen/provisioner/ansible_playbook.rb:883:in `ansible_roles_path'
D      C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/kitchen-ansible-0.46.4/lib/kitchen/provisioner/ansible_playbook.rb:396:in `run_command'
D      C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/test-kitchen-1.16.0/lib/kitchen/provisioner/base.rb:76:in `block in call'
D      C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/test-kitchen-1.16.0/lib/kitchen/transport/base.rb:89:in `initialize'
D      C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/test-kitchen-1.16.0/lib/kitchen/transport/ssh.rb:439:in `new'
D      C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/test-kitchen-1.16.0/lib/kitchen/transport/ssh.rb:439:in `create_new_connection'
D      C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/test-kitchen-1.16.0/lib/kitchen/transport/ssh.rb:90:in `connection'
D      C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/test-kitchen-1.16.0/lib/kitchen/provisioner/base.rb:68:in `call'
D      C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/test-kitchen-1.16.0/lib/kitchen/instance.rb:384:in `block in converge_action'
D      C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/test-kitchen-1.16.0/lib/kitchen/instance.rb:527:in `synchronize_or_call'
D      C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/test-kitchen-1.16.0/lib/kitchen/instance.rb:489:in `block in action'
D      C:/Ruby23-x64/lib/ruby/2.3.0/benchmark.rb:293:in `measure'
D      C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/test-kitchen-1.16.0/lib/kitchen/instance.rb:488:in `action'
D      C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/test-kitchen-1.16.0/lib/kitchen/instance.rb:380:in `converge_action'
D      C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/test-kitchen-1.16.0/lib/kitchen/instance.rb:359:in `block in transition_to'
D      C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/test-kitchen-1.16.0/lib/kitchen/instance.rb:358:in `each'
D      C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/test-kitchen-1.16.0/lib/kitchen/instance.rb:358:in `transition_to'
D      C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/test-kitchen-1.16.0/lib/kitchen/instance.rb:135:in `converge'
D      C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/test-kitchen-1.16.0/lib/kitchen/command.rb:197:in `public_send'
D      C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/test-kitchen-1.16.0/lib/kitchen/command.rb:197:in `run_action_in_thread'
D      C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/test-kitchen-1.16.0/lib/kitchen/command.rb:169:in `block (2 levels) in run_action'
D      ----End Backtrace-----
D      ---Nested Exception---
D      Class: Kitchen::ActionFailed
D      Message: Failed to complete #converge action: [undefined method `each' for nil:NilClass]
D      ----------------------
D      ------Backtrace-------
D      C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/kitchen-ansible-0.46.4/lib/kitchen/provisioner/ansible_playbook.rb:883:in `ansible_roles_path'
D      C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/kitchen-ansible-0.46.4/lib/kitchen/provisioner/ansible_playbook.rb:396:in `run_command'
D      C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/test-kitchen-1.16.0/lib/kitchen/provisioner/base.rb:76:in `block in call'
D      C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/test-kitchen-1.16.0/lib/kitchen/transport/base.rb:89:in `initialize'
D      C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/test-kitchen-1.16.0/lib/kitchen/transport/ssh.rb:439:in `new'
D      C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/test-kitchen-1.16.0/lib/kitchen/transport/ssh.rb:439:in `create_new_connection'
D      C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/test-kitchen-1.16.0/lib/kitchen/transport/ssh.rb:90:in `connection'
D      C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/test-kitchen-1.16.0/lib/kitchen/provisioner/base.rb:68:in `call'
D      C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/test-kitchen-1.16.0/lib/kitchen/instance.rb:384:in `block in converge_action'
D      C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/test-kitchen-1.16.0/lib/kitchen/instance.rb:527:in `synchronize_or_call'
D      C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/test-kitchen-1.16.0/lib/kitchen/instance.rb:489:in `block in action'
D      C:/Ruby23-x64/lib/ruby/2.3.0/benchmark.rb:293:in `measure'
D      C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/test-kitchen-1.16.0/lib/kitchen/instance.rb:488:in `action'
D      C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/test-kitchen-1.16.0/lib/kitchen/instance.rb:380:in `converge_action'
D      C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/test-kitchen-1.16.0/lib/kitchen/instance.rb:359:in `block in transition_to'
D      C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/test-kitchen-1.16.0/lib/kitchen/instance.rb:358:in `each'
D      C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/test-kitchen-1.16.0/lib/kitchen/instance.rb:358:in `transition_to'
D      C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/test-kitchen-1.16.0/lib/kitchen/instance.rb:135:in `converge'
D      C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/test-kitchen-1.16.0/lib/kitchen/command.rb:197:in `public_send'
D      C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/test-kitchen-1.16.0/lib/kitchen/command.rb:197:in `run_action_in_thread'
D      C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/test-kitchen-1.16.0/lib/kitchen/command.rb:169:in `block (2 levels) in run_action'
D      ----End Backtrace-----

So line 883 on ansible_playbook.rb. Perhaps a path complete if the path is relative?

**Comment by neillturner** [comment]
To support  ../ we need to look at using the
File.expand_path
to handle this similar to:
Expand the path to the ansible vault password file #234

**Comment by mikef-nl** [comment]
Added and tested additional_copy_path with the path expansion for relative paths.

**Comment by neillturner** [comment]
thanks for that i started looking at it but not written anything yet. I will merge this week after testing. I'm also going to add File.expand_path to a couple other parameters as well.

**Comment by mikef-nl** [comment]
Any idea when you will get a chance to merge this?

**Comment by neillturner** [comment]
fixed in version 0.47.0 closed.
