### ISSUE TITLE
Windows Guest Support

### ISSUE THREAD

**Issue by johnjelinek** [neillturner/kitchen-ansible#246]
Vagrant supports Windows VMs. Ansible can execute commands on windows VMs when the ansible controller runs from a mac/linux host. So if I'm running kitchen (and vagrant) from mac/linux, is there already windows guest support with the kitchen-ansible test kitchen plugin?

**Comment by neillturner** [comment]
the is another kitchen plugin kitchen-ansiblepush that enables you to run ansible on your workstation and communicate with windows vm.
my kitchen-ansible  plugin requires a separate VM to run ansible and it can then provision a second vm that can be windows. 

I believe that with BASH for windows etc it will be possible to run ansible on a windows VM and then i will be able to support running ansible and prvisioner all on a windows VM. 

https://www.jeffgeerling.com/blog/running-ansible-within-windows
https://www.jeffgeerling.com/blog/2017/using-ansible-through-windows-10s-subsystem-linux

I see there are some Windows 10 free virtual vms at https://developer.microsoft.com/en-us/windows/downloads/virtual-machines

looks to me that windows 10 with bash for windows is like a linux box even down to ssh so my kitchn-ansible could work if you specify ubuntu and point it at the windows box and with the ssh credentials. 
But I haven't tested this.

**Comment by mikef-nl** [comment]
@johnjelinek The short answer is yes Windows guests are supported :)

**Comment by johnjelinek** [comment]
Is there an easy way to add steps to prep an older Windows box to support
Ansible (upgrade to Powershell 3.0 and .NET 4.5 and reboot and add a self
signed cert for WinRM) on kitchen create?

**Comment by mikef-nl** [comment]
Generally I would say use vagrant/packer to create a new box with it pre-installed. Alternatively you could use the vagrantfiles config option and add a custom provider for the box like:
`Vagrant.configure("2") do |c|
  c.vm.provision :shell do |shell|
    shell.path = "https://raw.githubusercontent.com/ansible/ansible/devel/examples/scripts/ConfigureRemotingForAnsible.ps1"
  end
end`

**Comment by mikef-nl** [comment]
@johnjelinek Did you have any luck with the suggested solution?

**Comment by neillturner** [comment]
Yes i use packer/vagrant and if you can create a powershell script to do what you want with a vanilla windows box then packer can automate the creation of the base image.

**Comment by johnjelinek** [comment]
I also went the Packer route. Thanks!

**Comment by mikef-nl** [comment]
Think that means this one can be closed?

**Comment by johnjelinek** [comment]
yap, thanks!
