### ISSUE TITLE
provisioner_option 'hosts' should allow multiple group names

### ISSUE THREAD

**Issue by gersilex** [neillturner/kitchen-ansible#247]
A host can be in multiple groups, not just one.

For example: A host may be in a group 'webservers' and in a group 'production'. When deploying, every host is definitely in either 'production' or 'staging' AND in either 'webservers' or 'dbservers'.

Programmatically I would think of allowing a list of `hosts` and creating a inventory block `for every hosts entry`.

**Comment by gersilex** [comment]
I can't seem to find the part in the code and need support, please.

**Comment by neillturner** [comment]
i think you should already be able to do this, let me check.

**Comment by gersilex** [comment]
Thanks. While this is a nice and powerful way to describe big inventories dynamically, especially for production, I'd rather have a quick, descriptive way of writing this into the `kitchen.yml`.

Example:
One group, working fine:
```
# kitchen.yml
provisioner:
  hosts: group1
```
```
# creates hosts file on converge
# vagrant@playbook-debian-86:~$ cat /tmp/kitchen/hosts
localhost ansible_connection=local
[group1]
localhost
```

Multiple Groups:
```
# kitchen.yml
  hosts:
    - group1
    - group2
```
```
# vagrant@playbook-debian-86:~$ cat /tmp/kitchen/hosts
localhost ansible_connection=local
[["group1", "group2"]]
localhost
```

Desired behaviour:
```
# vagrant@playbook-debian-86:~$ cat /tmp/kitchen/hosts
localhost ansible_connection=local
[group1]
localhost

[group2]
localhost
```

This means, I would like to change the way, the yaml is resolved to the ini-style file, without additional code in the ansible role, but instead in the kitchen-ansible directly?

Not being good at ruby, I may need your coding skill, though.

**Comment by neillturner** [comment]
I have the code in https://github.com/neillturner/kitchen-puppet see hiera_writer_files option. this allows instream puppet hiera yaml files in kitchen.yml. 
so can lift the code and do for kitchen ansible

**Comment by neillturner** [comment]
```
      def prepare_hosts
        return if ansible_inventory
        info('Preparing hosts file')

        if config[:hosts].nil?
          fail 'No hosts have been set. Please specify one in .kitchen.yml'
        else
          debug("Using host from #{hosts}")
          File.open(File.join(sandbox_path, 'hosts'), 'wb') do |file|
            file.write("localhost ansible_connection=local\n[#{hosts}]\nlocalhost\n")
          end
        end
      end

goes to 

      def prepare_hosts
        return if ansible_inventory
        info('Preparing hosts file')

        if config[:hosts].nil?
          fail 'No hosts have been set. Please specify one in .kitchen.yml'
        elsif config[:hosts].is_a?(Array)
          debug("Using an array of hosts from #{hosts}")
          File.open(File.join(sandbox_path, 'hosts'), 'wb') do |file|
            hoststring="localhost ansible_connection=local\n"
            config[:hosts].each do |h|
              hoststring+="[#{h}]\nlocalhost\n"
            end
            file.write(hoststring)
          end
        else
          debug("Using host from #{hosts}")
          File.open(File.join(sandbox_path, 'hosts'), 'wb') do |file|
            file.write("localhost ansible_connection=local\n[#{hosts}]\nlocalhost\n")
          end
        end
      end
```

**Comment by gersilex** [comment]
Looks good. I will test it tomorrow and report back. :+1:

**Comment by mikef-nl** [comment]
@gersilex Any luck with the testing?

**Comment by gersilex** [comment]
Unfortunately I couldn't test it, yet. This was a hell of a week. Will
definitely keep you updated.

Mike F <notifications@github.com> schrieb am Fr., 23. Juni 2017, 08:52:

**Comment by neillturner** [comment]
I will test on the the weekend and then put into the code. no worries. thanks for all your help.

**Comment by neillturner** [comment]
in version 0.47.2  closed
