### ISSUE TITLE
Debian 9

### ISSUE THREAD

**Issue by mimek** [neillturner/kitchen-ansible#251]
Hello,
it seems that there's a problem with ansible installation on Debian 9. I'm using bento/debian-9.0 image and ansible installation hangs on:

> Hit:1 http://security.debian.org/debian-security stretch/updates InRelease
> Get:2 http://ppa.launchpad.net/ansible/ansible/ubuntu trusty InRelease [16.0 kB]
> Ign:2 http://ppa.launchpad.net/ansible/ansible/ubuntu trusty InRelease
> Get:3 http://ppa.launchpad.net/ansible/ansible/ubuntu trusty/main amd64 Packages [523 B]
> Get:4 http://ppa.launchpad.net/ansible/ansible/ubuntu trusty/main Translation-en [322 B]
> Ign:5 http://cdn-fastly.deb.debian.org/debian stretch InRelease
> Hit:6 http://cdn-fastly.deb.debian.org/debian stretch-updates InRelease
> Hit:7 http://cdn-fastly.deb.debian.org/debian stretch Release
> Fetched 16.8 kB in 0s (26.8 kB/s)
> Reading package lists... Done
>        W: GPG error: http://ppa.launchpad.net/ansible/ansible/ubuntu trusty InRelease: The following > signatures couldn't be verified because the public key is not available: NO_PUBKEY 93C4A3FD7BB9C367
>        W: The repository 'http://ppa.launchpad.net/ansible/ansible/ubuntu trusty InRelease' is not signed.
>        N: Data from such a repository can't be authenticated and is therefore potentially dangerous to use.
>       N: See apt-secure(8) manpage for repository creation and user configuration details.

It will proceed if I manuallly install pacakge: dirmngr. I can't see any possibility to do this before ansible is being installed by kitchen-ansible on fresh image - is there any?

Kind regards
mimek

**Comment by neillturner** [comment]
Use the custom_pre_install_command parameter to put your command to  install pacakge: dirmngr.
