### ISSUE TITLE
Autogenerate ansible inventory

### ISSUE THREAD

**Issue by mikef-nl** [neillturner/kitchen-ansible#270]
I'm not sure on how difficult this would be to implement. 
It would take what was in the .kitchen file and autogenerate a Ansible inventory hosts file.
This would need to get the IP of each server created in vagrant, its OS and relevant port to connect to.

**Comment by neillturner** [comment]
closing as i won't write the code for this however if anyone creates a pull request than i can incorporate. kitchen-ansible code pretty mature and stable now.
