### ISSUE TITLE
Pip installation fails with Ubuntu 18.04

### ISSUE THREAD

**Issue by quulah** [neillturner/kitchen-ansible#276]
Probably due to Ubuntu 18.04 having Python 3 by default and the packages have changed. It just doesn't find the `pip` command.

```
Installing ansible through pip
Extracting templates from packages: 100%
sudo: easy_install: command not found
sudo: pip: command not found
sudo: pip: command not found
...
bash: ansible-galaxy: command not found
```

If I manually install the `python-pip` package after the first try, it works. So the fix should be relatively straightforward.

`python-pip` exists for 16.04 too, so adding that to the list probably wouldn't break anything.

**Comment by quulah** [comment]
I created a quick pull request.

#277

**Comment by neillturner** [comment]
kitchen ansible 0.48.4 version released
