### ISSUE TITLE
cp: failed to access ‘/etc/ansible/.’: Not a directory

### ISSUE THREAD

**Issue by wolfman2g1** [neillturner/kitchen-ansible#28]
I've been trying to test some simple playbooks and i've been getting this error

cp: failed to access ‘/etc/ansible/.’: Not a directory

Here's the .kitchen.yaml

<pre> <code> 
---
driver:
  name: vagrant

provisioner:
  name: ansible_playbook
  playbook: nginx.yml
  #ansible_yum_repo: "https://download.fedoraproject.org/pub/epel/7/x86_64/e/epel-release-7-5.noarch.rpm"
  ansible_verbose: true
  ansible_verbosity: 3
  hosts: all

platforms:
  - name: centos-7.0

suites:
  - name: default
    run_list:
    attributes:
</code> </pre>

<pre><code>Transferring files to <default-centos-70>
I, [2015-02-10T00:05:30.318107 #55487]  INFO -- default-centos-70: cp: failed to access ‘/etc/ansible/.’: Not a directory
E, [2015-02-10T00:05:30.322554 #55487] ERROR -- default-centos-70: Converge failed on instance <default-centos-70>.
E, [2015-02-10T00:05:30.322680 #55487] ERROR -- default-centos-70: ------Exception-------
E, [2015-02-10T00:05:30.322719 #55487] ERROR -- default-centos-70: Class: Kitchen::ActionFailed
E, [2015-02-10T00:05:30.322744 #55487] ERROR -- default-centos-70: Message: SSH exited (1) for command: [sudo -E cp /tmp/kitchen/ansible.cfg /etc/ansible && sudo -E cp -r /tmp/kitchen/group_vars /etc/ansible/. && sudo -E cp -r /tmp/kitchen/host_vars /etc/ansible/.]
E, [2015-02-10T00:05:30.322766 #55487] ERROR -- default-centos-70: ---Nested Exception---
E, [2015-02-10T00:05:30.322785 #55487] ERROR -- default-centos-70: Class: Kitchen::SSHFailed
E, [2015-02-10T00:05:30.322819 #55487] ERROR -- default-centos-70: Message: SSH exited (1) for command: [sudo -E cp /tmp/kitchen/ansible.cfg /etc/ansible && sudo -E cp -r /tmp/kitchen/group_vars /etc/ansible/. && sudo -E cp -r /tmp/kitchen/host_vars /etc/ansible/.]
E, [2015-02-10T00:05:30.322844 #55487] ERROR -- default-centos-70: ------Backtrace-------
E, [2015-02-10T00:05:30.322864 #55487] ERROR -- default-centos-70: /Users/rjones/.rvm/gems/ruby-2.2.0@global/gems/test-kitchen-1.3.1/lib/kitchen/driver/ssh_base.rb:152:in `rescue in run_remote'
E, [2015-02-10T00:05:30.322885 #55487] ERROR -- default-centos-70: /Users/rjones/.rvm/gems/ruby-2.2.0@global/gems/test-kitchen-1.3.1/lib/kitchen/driver/ssh_base.rb:148:in `run_remote'
E, [2015-02-10T00:05:30.322927 #55487] ERROR -- default-centos-70: /Users/rjones/.rvm/gems/ruby-2.2.0@global/gems/test-kitchen-1.3.1/lib/kitchen/driver/ssh_base.rb:49:in `block in converge'
E, [2015-02-10T00:05:30.322946 #55487] ERROR -- default-centos-70: /Users/rjones/.rvm/gems/ruby-2.2.0@global/gems/test-kitchen-1.3.1/lib/kitchen/ssh.rb:70:in `initialize'
E, [2015-02-10T00:05:30.322965 #55487] ERROR -- default-centos-70: /Users/rjones/.rvm/gems/ruby-2.2.0@global/gems/test-kitchen-1.3.1/lib/kitchen/driver/ssh_base.rb:45:in `new'
E, [2015-02-10T00:05:30.322985 #55487] ERROR -- default-centos-70: /Users/rjones/.rvm/gems/ruby-2.2.0@global/gems/test-kitchen-1.3.1/lib/kitchen/driver/ssh_base.rb:45:in `converge'
E, [2015-02-10T00:05:30.323003 #55487] ERROR -- default-centos-70: /Users/rjones/.rvm/gems/ruby-2.2.0/gems/kitchen-vagrant-0.15.0/lib/kitchen/driver/vagrant.rb:75:in `converge'
E, [2015-02-10T00:05:30.323023 #55487] ERROR -- default-centos-70: /Users/rjones/.rvm/gems/ruby-2.2.0@global/gems/test-kitchen-1.3.1/lib/kitchen/instance.rb:352:in `public_send'
E, [2015-02-10T00:05:30.323036 #55487] ERROR -- default-centos-70: /Users/rjones/.rvm/gems/ruby-2.2.0@global/gems/test-kitchen-1.3.1/lib/kitchen/instance.rb:352:in `block in perform_action'
E, [2015-02-10T00:05:30.323046 #55487] ERROR -- default-centos-70: /Users/rjones/.rvm/gems/ruby-2.2.0@global/gems/test-kitchen-1.3.1/lib/kitchen/instance.rb:416:in `call'
E, [2015-02-10T00:05:30.323056 #55487] ERROR -- default-centos-70: /Users/rjones/.rvm/gems/ruby-2.2.0@global/gems/test-kitchen-1.3.1/lib/kitchen/instance.rb:416:in `synchronize_or_call'
E, [2015-02-10T00:05:30.323066 #55487] ERROR -- default-centos-70: /Users/rjones/.rvm/gems/ruby-2.2.0@global/gems/test-kitchen-1.3.1/lib/kitchen/instance.rb:381:in `block in action'
E, [2015-02-10T00:05:30.323076 #55487] ERROR -- default-centos-70: /Users/rjones/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/benchmark.rb:288:in `measure'
E, [2015-02-10T00:05:30.323087 #55487] ERROR -- default-centos-70: /Users/rjones/.rvm/gems/ruby-2.2.0@global/gems/test-kitchen-1.3.1/lib/kitchen/instance.rb:380:in `action'
E, [2015-02-10T00:05:30.323097 #55487] ERROR -- default-centos-70: /Users/rjones/.rvm/gems/ruby-2.2.0@global/gems/test-kitchen-1.3.1/lib/kitchen/instance.rb:352:in `perform_action'
E, [2015-02-10T00:05:30.323107 #55487] ERROR -- default-centos-70: /Users/rjones/.rvm/gems/ruby-2.2.0@global/gems/test-kitchen-1.3.1/lib/kitchen/instance.rb:312:in `converge_action'
E, [2015-02-10T00:05:30.323117 #55487] ERROR -- default-centos-70: /Users/rjones/.rvm/gems/ruby-2.2.0@global/gems/test-kitchen-1.3.1/lib/kitchen/instance.rb:292:in `block in transition_to'
E, [2015-02-10T00:05:30.323127 #55487] ERROR -- default-centos-70: /Users/rjones/.rvm/gems/ruby-2.2.0@global/gems/test-kitchen-1.3.1/lib/kitchen/instance.rb:291:in `each'
E, [2015-02-10T00:05:30.323137 #55487] ERROR -- default-centos-70: /Users/rjones/.rvm/gems/ruby-2.2.0@global/gems/test-kitchen-1.3.1/lib/kitchen/instance.rb:291:in `transition_to'
E, [2015-02-10T00:05:30.323147 #55487] ERROR -- default-centos-70: /Users/rjones/.rvm/gems/ruby-2.2.0@global/gems/test-kitchen-1.3.1/lib/kitchen/instance.rb:130:in `converge'
E, [2015-02-10T00:05:30.323157 #55487] ERROR -- default-centos-70: /Users/rjones/.rvm/gems/ruby-2.2.0@global/gems/test-kitchen-1.3.1/lib/kitchen/command.rb:176:in `public_send'
E, [2015-02-10T00:05:30.323176 #55487] ERROR -- default-centos-70: /Users/rjones/.rvm/gems/ruby-2.2.0@global/gems/test-kitchen-1.3.1/lib/kitchen/command.rb:176:in `block (2 levels) in run_action'

</code> </pre>

I just have an ansible directory where i keep all my playbooks and host file. I'm assuming that I need to override the location /etc/ansible some how but looking at the kitchen-ansible and test-kitchen docs I haven't been able to figure out how

**Comment by trinitronx** [comment]
@wolfman2g1:  I've run into this bug also.  The problem is that the ansible package that gets installed inside the `test-kitchen` VM on some platforms does not contain the `/etc/ansible` directory.

The reason you're seeing the failure is because `kitchen-ansible` is naively copying `[ 'ansible.cfg', 'group_vars', 'host_vars' ]` into  `/etc/ansible` in the VM expecting it to be there, but that path doesn't exist.

I think this is a bug. I've made a patch locally that I've been using on my development version of `kitchen-ansible`  I just haven't gotten around to making a PR due to time constraints and other priorities at work.

**Comment by jolexa** [comment]
Could one argue that this is a packing error in the distro?

**Comment by trinitronx** [comment]
@jolexa: Yes, this is a packaging error in the distro.  I've added the workaround in #30 since we're downstream of the packaging and have less ability to repackage & get things fixed ourselves for now.

**Comment by jolexa** [comment]
Cool, then we are in agreement. Did anyone file an upstream bug?

**Comment by trinitronx** [comment]
@jolexa: A cursory check doesn't turn [anything up here](https://bugzilla.redhat.com/buglist.cgi?component=ansible&product=Fedora%20EPEL).  Perhaps we should file a bug?
