### ISSUE TITLE
`stat': No such file or directory @ rb_file_s_stat

### ISSUE THREAD

**Issue by e-moshaya** [neillturner/kitchen-ansible#295]
Occasionally, when I run kitchen converge, kitchen fails when trying to transfer files to the ec2 instance with the following error: 

`-----> Creating <default-amazon-linux-hardened>...
       If you are not using an account that qualifies under the AWS
free-tier, you may be charged to run these suites. The charge
should be minimal, but neither Test Kitchen nor its maintainers
are responsible for your incurred costs.

       Instance <i-0b0dc50bafec2e737> requested.
       Polling AWS for existence, attempt 0...
       Attempting to tag the instance, 0 retries
       EC2 instance <i-0b0dc50bafec2e737> created.
       Waited 0/300s for instance <i-0b0dc50bafec2e737> volumes to be ready.
       Waited 0/300s for instance <i-0b0dc50bafec2e737> to become ready.
       Waited 5/300s for instance <i-0b0dc50bafec2e737> to become ready.
       Waited 10/300s for instance <i-0b0dc50bafec2e737> to become ready.
       EC2 instance <i-0b0dc50bafec2e737> ready (hostname: 35.178.201.133).
       Waiting for SSH service on 35.178.201.133:22, retrying in 3 seconds
       [SSH] Established
       Finished creating <default-amazon-linux-hardened> (0m26.29s).
-----> Converging <default-amazon-linux-hardened>...
       Preparing files for transfer
       Preparing playbook
       Preparing inventory
       Preparing modules
       nothing to do for modules
       Preparing roles
       Preparing ansible.cfg file
       Empty ansible.cfg generated
       Preparing group_vars
       nothing to do for group_vars
       Preparing additional_copy_path
       Preparing host_vars
       nothing to do for host_vars
       Preparing hosts file
       Preparing spec
       nothing to do for spec
       Preparing library plugins
       nothing to do for library plugins
       Preparing callback plugins
       nothing to do for callback plugins
       Preparing filter_plugins
       nothing to do for filter_plugins
       Preparing lookup_plugins
       nothing to do for lookup_plugins
       Preparing ansible vault password
       Preparing additional_ssh_private_keys
       nothing to do for additional_ssh_private_keys
       Finished Preparing files for transfer
       Installing ansible through pip
       which: no ansible in (/usr/local/bin:/usr/bin)
       sudo: apt-get: command not found
       sudo: apt-get: command not found
-----> Installing Chef Omnibus to install busser to run tests
       downloading https://www.chef.io/chef/install.sh
         to file /tmp/install.sh
       trying wget...
       warning: /tmp/install.sh.2549/chef-14.6.47-1.el7.x86_64.rpm: Header V4 DSA/SHA1 Signature, key ID 83ef826a: NOKEY
       Transferring files to <default-amazon-linux-hardened>
#<Thread:0x00007fa80ab3f290@/usr/local/lib/ruby/gems/2.5.0/gems/test-kitchen-1.23.2/lib/kitchen/command.rb:167 run> terminated with exception (report_on_exception is true):
Traceback (most recent call last):
	22: from /usr/local/lib/ruby/gems/2.5.0/gems/test-kitchen-1.23.2/lib/kitchen/command.rb:169:in `block (2 levels) in run_action'
	21: from /usr/local/lib/ruby/gems/2.5.0/gems/test-kitchen-1.23.2/lib/kitchen/command.rb:205:in `run_action_in_thread'
	20: from /usr/local/lib/ruby/gems/2.5.0/gems/test-kitchen-1.23.2/lib/kitchen/instance.rb:299:in `cleanup!'
	19: from /usr/local/lib/ruby/gems/2.5.0/gems/test-kitchen-1.23.2/lib/kitchen/transport/ssh.rb:106:in `cleanup!'
	18: from /usr/local/lib/ruby/gems/2.5.0/gems/test-kitchen-1.23.2/lib/kitchen/transport/ssh.rb:129:in `close'
	17: from /usr/local/lib/ruby/gems/2.5.0/gems/net-ssh-4.2.0/lib/net/ssh/connection/session.rb:124:in `close'
	16: from /usr/local/lib/ruby/gems/2.5.0/gems/net-ssh-4.2.0/lib/net/ssh/connection/session.rb:178:in `loop'
	15: from /usr/local/lib/ruby/gems/2.5.0/gems/net-ssh-4.2.0/lib/net/ssh/connection/session.rb:178:in `loop'
	14: from /usr/local/lib/ruby/gems/2.5.0/gems/net-ssh-4.2.0/lib/net/ssh/connection/session.rb:178:in `block in loop'
	13: from /usr/local/lib/ruby/gems/2.5.0/gems/net-ssh-4.2.0/lib/net/ssh/connection/session.rb:225:in `process'
	12: from /usr/local/lib/ruby/gems/2.5.0/gems/net-ssh-4.2.0/lib/net/ssh/connection/event_loop.rb:27:in `process'
	11: from /usr/local/lib/ruby/gems/2.5.0/gems/net-ssh-4.2.0/lib/net/ssh/connection/event_loop.rb:99:in `ev_preprocess'
	10: from /usr/local/lib/ruby/gems/2.5.0/gems/net-ssh-4.2.0/lib/net/ssh/connection/event_loop.rb:99:in `each'
	 9: from /usr/local/lib/ruby/gems/2.5.0/gems/net-ssh-4.2.0/lib/net/ssh/connection/session.rb:247:in `ev_preprocess'
	 8: from /usr/local/lib/ruby/gems/2.5.0/gems/net-ssh-4.2.0/lib/net/ssh/connection/session.rb:538:in `each_channel'
	 7: from /usr/local/lib/ruby/gems/2.5.0/gems/net-ssh-4.2.0/lib/net/ssh/connection/session.rb:538:in `each'
	 6: from /usr/local/lib/ruby/gems/2.5.0/gems/net-ssh-4.2.0/lib/net/ssh/connection/session.rb:247:in `block in ev_preprocess'
	 5: from /usr/local/lib/ruby/gems/2.5.0/gems/net-ssh-4.2.0/lib/net/ssh/connection/channel.rb:320:in `process'
	 4: from /usr/local/lib/ruby/gems/2.5.0/gems/net-scp-1.2.1/lib/net/scp.rb:369:in `block (3 levels) in start_command'
	 3: from /usr/local/lib/ruby/gems/2.5.0/gems/net-scp-1.2.1/lib/net/scp.rb:400:in `await_response_state'
	 2: from /usr/local/lib/ruby/gems/2.5.0/gems/net-scp-1.2.1/lib/net/scp/upload.rb:103:in `next_item_state'
	 1: from /usr/local/lib/ruby/gems/2.5.0/gems/net-scp-1.2.1/lib/net/scp/upload.rb:117:in `set_current'
/usr/local/lib/ruby/gems/2.5.0/gems/net-scp-1.2.1/lib/net/scp/upload.rb:117:in `stat': No such file or directory @ rb_file_s_stat - /var/folders/2b/1__l5btd66ldxhhtvp1fp6h80000gp/T/default-amazon-linux-hardened-sandbox-20181103-53266-tllcic/roles/jenkins-master-ansible-role (Errno::ENOENT)
bundler: failed to load command: kitchen (/usr/local/bin/kitchen)
Errno::ENOENT: No such file or directory @ rb_file_s_stat - /var/folders/2b/1__l5btd66ldxhhtvp1fp6h80000gp/T/default-amazon-linux-hardened-sandbox-20181103-53266-tllcic/roles/jenkins-master-ansible-role
  /usr/local/lib/ruby/gems/2.5.0/gems/net-scp-1.2.1/lib/net/scp/upload.rb:117:in `stat'
  /usr/local/lib/ruby/gems/2.5.0/gems/net-scp-1.2.1/lib/net/scp/upload.rb:117:in `set_current'
  /usr/local/lib/ruby/gems/2.5.0/gems/net-scp-1.2.1/lib/net/scp/upload.rb:103:in `next_item_state'
  /usr/local/lib/ruby/gems/2.5.0/gems/net-scp-1.2.1/lib/net/scp.rb:400:in `await_response_state'
  /usr/local/lib/ruby/gems/2.5.0/gems/net-scp-1.2.1/lib/net/scp.rb:369:in `block (3 levels) in start_command'
  /usr/local/lib/ruby/gems/2.5.0/gems/net-ssh-4.2.0/lib/net/ssh/connection/channel.rb:320:in `process'
  /usr/local/lib/ruby/gems/2.5.0/gems/net-ssh-4.2.0/lib/net/ssh/connection/session.rb:247:in `block in ev_preprocess'
  /usr/local/lib/ruby/gems/2.5.0/gems/net-ssh-4.2.0/lib/net/ssh/connection/session.rb:538:in `each'
  /usr/local/lib/ruby/gems/2.5.0/gems/net-ssh-4.2.0/lib/net/ssh/connection/session.rb:538:in `each_channel'
  /usr/local/lib/ruby/gems/2.5.0/gems/net-ssh-4.2.0/lib/net/ssh/connection/session.rb:247:in `ev_preprocess'
  /usr/local/lib/ruby/gems/2.5.0/gems/net-ssh-4.2.0/lib/net/ssh/connection/event_loop.rb:99:in `each'
  /usr/local/lib/ruby/gems/2.5.0/gems/net-ssh-4.2.0/lib/net/ssh/connection/event_loop.rb:99:in `ev_preprocess'
  /usr/local/lib/ruby/gems/2.5.0/gems/net-ssh-4.2.0/lib/net/ssh/connection/event_loop.rb:27:in `process'
  /usr/local/lib/ruby/gems/2.5.0/gems/net-ssh-4.2.0/lib/net/ssh/connection/session.rb:225:in `process'
  /usr/local/lib/ruby/gems/2.5.0/gems/net-ssh-4.2.0/lib/net/ssh/connection/session.rb:178:in `block in loop'
  /usr/local/lib/ruby/gems/2.5.0/gems/net-ssh-4.2.0/lib/net/ssh/connection/session.rb:178:in `loop'
  /usr/local/lib/ruby/gems/2.5.0/gems/net-ssh-4.2.0/lib/net/ssh/connection/session.rb:178:in `loop'
  /usr/local/lib/ruby/gems/2.5.0/gems/net-ssh-4.2.0/lib/net/ssh/connection/session.rb:124:in `close'
  /usr/local/lib/ruby/gems/2.5.0/gems/test-kitchen-1.23.2/lib/kitchen/transport/ssh.rb:129:in `close'
  /usr/local/lib/ruby/gems/2.5.0/gems/test-kitchen-1.23.2/lib/kitchen/transport/ssh.rb:106:in `cleanup!'
  /usr/local/lib/ruby/gems/2.5.0/gems/test-kitchen-1.23.2/lib/kitchen/instance.rb:299:in `cleanup!'
  /usr/local/lib/ruby/gems/2.5.0/gems/test-kitchen-1.23.2/lib/kitchen/command.rb:205:in `run_action_in_thread'
  /usr/local/lib/ruby/gems/2.5.0/gems/test-kitchen-1.23.2/lib/kitchen/command.rb:169:in `block (2 levels) in run_action'
make: *** [kitchen-converge] Error 1`

My .kitchen.yml config:

`---
driver:
  name: ec2
  aws_ssh_key_id: test-kitchen
  instance_type: t3.nano
  security_group_ids: ["sg-0fffff6"]
  region: eu-west-1
  availability_zone: eu-west-1a
  subnet_id: subnet-ffefefefe
  iam_profile_name: test-kitchen
  instance_initiated_shutdown_behavior: terminate
  interface: public
  tags: { created-by: "test-kitchen",
          RunningHours: "On Demand",
          env: "build" }

transport:
  ssh_key: ~/.ssh/test-kitchen
  connection_timeout: 10
  connection_retries: 5
  username: ec2-user

provisioner:
  name: ansible_playbook
  playbook: test/default.yml
  roles_path: ../../roles
  hosts: all
  require_ansible_repo: false
  require_ansible_omnibus: false
  require_chef_omnibus: false
  ansible_verbose: false
  idempotency_test: false
  ansible_diff: true
  max_retries: 2
  require_chef_for_busser: true
  require_pip: true
  enable_yum_epel: true

verifier:
  sudo_path: true

platforms:
- name: amazon-linux
  driver:
    image_search:
      owner-id: "137112412989"
      name: amzn2-ami-hvm-*gp2

- name: amazon-linux-hardened
  driver:
    image_search:
      owner-id: "679593333241"
      name: Hard_Amazon_Linux_2_Oct18-e47cfbd4-28f7-4010-a6a2-4d3f80938f7b-ami-074f5cdd220c5534f.4

suites:
  - name: default
`

kitchen log:

`I, [2018-11-03T23:09:20.545342 #53266]  INFO -- default-amazon-linux-hardened: -----> Creating <default-amazon-linux-hardened>...
I, [2018-11-03T23:09:21.218783 #53266]  INFO -- default-amazon-linux-hardened: If you are not using an account that qualifies under the AWS
free-tier, you may be charged to run these suites. The charge
should be minimal, but neither Test Kitchen nor its maintainers
are responsible for your incurred costs.

I, [2018-11-03T23:09:22.471018 #53266]  INFO -- default-amazon-linux-hardened: Instance <i-0b0dc50bafec2e737> requested.
I, [2018-11-03T23:09:22.471198 #53266]  INFO -- default-amazon-linux-hardened: Polling AWS for existence, attempt 0...
I, [2018-11-03T23:09:23.105592 #53266]  INFO -- default-amazon-linux-hardened: Attempting to tag the instance, 0 retries
I, [2018-11-03T23:09:23.375975 #53266]  INFO -- default-amazon-linux-hardened: EC2 instance <i-0b0dc50bafec2e737> created.
I, [2018-11-03T23:09:23.376213 #53266]  INFO -- default-amazon-linux-hardened: Waited 0/300s for instance <i-0b0dc50bafec2e737> volumes to be ready.
I, [2018-11-03T23:09:25.019320 #53266]  INFO -- default-amazon-linux-hardened: Waited 0/300s for instance <i-0b0dc50bafec2e737> to become ready.
I, [2018-11-03T23:09:30.155961 #53266]  INFO -- default-amazon-linux-hardened: Waited 5/300s for instance <i-0b0dc50bafec2e737> to become ready.
I, [2018-11-03T23:09:35.566093 #53266]  INFO -- default-amazon-linux-hardened: Waited 10/300s for instance <i-0b0dc50bafec2e737> to become ready.
I, [2018-11-03T23:09:35.704053 #53266]  INFO -- default-amazon-linux-hardened: EC2 instance <i-0b0dc50bafec2e737> ready (hostname: 35.178.201.133).
I, [2018-11-03T23:09:42.739316 #53266]  INFO -- default-amazon-linux-hardened: Waiting for SSH service on 35.178.201.133:22, retrying in 3 seconds
I, [2018-11-03T23:09:46.833811 #53266]  INFO -- default-amazon-linux-hardened: [SSH] Established
I, [2018-11-03T23:09:46.836150 #53266]  INFO -- default-amazon-linux-hardened: Finished creating <default-amazon-linux-hardened> (0m26.29s).
I, [2018-11-03T23:09:46.836441 #53266]  INFO -- default-amazon-linux-hardened: -----> Converging <default-amazon-linux-hardened>...
I, [2018-11-03T23:09:46.837589 #53266]  INFO -- default-amazon-linux-hardened: Preparing files for transfer
I, [2018-11-03T23:09:46.837731 #53266]  INFO -- default-amazon-linux-hardened: Preparing playbook
I, [2018-11-03T23:09:46.838555 #53266]  INFO -- default-amazon-linux-hardened: Preparing inventory
I, [2018-11-03T23:09:46.838711 #53266]  INFO -- default-amazon-linux-hardened: Preparing modules
I, [2018-11-03T23:09:46.839188 #53266]  INFO -- default-amazon-linux-hardened: nothing to do for modules
I, [2018-11-03T23:09:46.839367 #53266]  INFO -- default-amazon-linux-hardened: Preparing roles
I, [2018-11-03T23:09:46.880784 #53266]  INFO -- default-amazon-linux-hardened: Preparing ansible.cfg file
I, [2018-11-03T23:09:46.881038 #53266]  INFO -- default-amazon-linux-hardened: Empty ansible.cfg generated
I, [2018-11-03T23:09:46.881425 #53266]  INFO -- default-amazon-linux-hardened: Preparing group_vars
I, [2018-11-03T23:09:46.882072 #53266]  INFO -- default-amazon-linux-hardened: nothing to do for group_vars
I, [2018-11-03T23:09:46.882137 #53266]  INFO -- default-amazon-linux-hardened: Preparing additional_copy_path
I, [2018-11-03T23:09:46.882324 #53266]  INFO -- default-amazon-linux-hardened: Preparing host_vars
I, [2018-11-03T23:09:46.882565 #53266]  INFO -- default-amazon-linux-hardened: nothing to do for host_vars
I, [2018-11-03T23:09:46.882616 #53266]  INFO -- default-amazon-linux-hardened: Preparing hosts file
I, [2018-11-03T23:09:46.882832 #53266]  INFO -- default-amazon-linux-hardened: Preparing spec
I, [2018-11-03T23:09:46.883126 #53266]  INFO -- default-amazon-linux-hardened: nothing to do for spec
I, [2018-11-03T23:09:46.883201 #53266]  INFO -- default-amazon-linux-hardened: Preparing library plugins
I, [2018-11-03T23:09:46.883647 #53266]  INFO -- default-amazon-linux-hardened: nothing to do for library plugins
I, [2018-11-03T23:09:46.883712 #53266]  INFO -- default-amazon-linux-hardened: Preparing callback plugins
I, [2018-11-03T23:09:46.884328 #53266]  INFO -- default-amazon-linux-hardened: nothing to do for callback plugins
I, [2018-11-03T23:09:46.884394 #53266]  INFO -- default-amazon-linux-hardened: Preparing filter_plugins
I, [2018-11-03T23:09:46.884992 #53266]  INFO -- default-amazon-linux-hardened: nothing to do for filter_plugins
I, [2018-11-03T23:09:46.885043 #53266]  INFO -- default-amazon-linux-hardened: Preparing lookup_plugins
I, [2018-11-03T23:09:46.885649 #53266]  INFO -- default-amazon-linux-hardened: nothing to do for lookup_plugins
I, [2018-11-03T23:09:46.885886 #53266]  INFO -- default-amazon-linux-hardened: Preparing ansible vault password
I, [2018-11-03T23:09:46.886116 #53266]  INFO -- default-amazon-linux-hardened: Preparing additional_ssh_private_keys
I, [2018-11-03T23:09:46.886630 #53266]  INFO -- default-amazon-linux-hardened: nothing to do for additional_ssh_private_keys
I, [2018-11-03T23:09:46.886714 #53266]  INFO -- default-amazon-linux-hardened: Finished Preparing files for transfer
I, [2018-11-03T23:09:46.887101 #53266]  INFO -- default-amazon-linux-hardened: Installing ansible through pip
I, [2018-11-03T23:09:46.972117 #53266]  INFO -- default-amazon-linux-hardened: which: no ansible in (/usr/local/bin:/usr/bin)
I, [2018-11-03T23:09:46.984815 #53266]  INFO -- default-amazon-linux-hardened: sudo: apt-get: command not found
I, [2018-11-03T23:09:46.997057 #53266]  INFO -- default-amazon-linux-hardened: sudo: apt-get: command not found
I, [2018-11-03T23:10:04.339911 #53266]  INFO -- default-amazon-linux-hardened: -----> Installing Chef Omnibus to install busser to run tests
I, [2018-11-03T23:10:04.342163 #53266]  INFO -- default-amazon-linux-hardened: downloading https://www.chef.io/chef/install.sh
I, [2018-11-03T23:10:04.342699 #53266]  INFO -- default-amazon-linux-hardened:   to file /tmp/install.sh
I, [2018-11-03T23:10:04.343222 #53266]  INFO -- default-amazon-linux-hardened: trying wget...
I, [2018-11-03T23:10:05.671304 #53266]  INFO -- default-amazon-linux-hardened: warning: /tmp/install.sh.2549/chef-14.6.47-1.el7.x86_64.rpm: Header V4 DSA/SHA1 Signature, key ID 83ef826a: NOKEY
I, [2018-11-03T23:10:10.293236 #53266]  INFO -- default-amazon-linux-hardened: Transferring files to <default-amazon-linux-hardened>
E, [2018-11-03T23:10:10.597519 #53266] ERROR -- default-amazon-linux-hardened: Converge failed on instance <default-amazon-linux-hardened>.
E, [2018-11-03T23:10:10.597632 #53266] ERROR -- default-amazon-linux-hardened: ------Exception-------
E, [2018-11-03T23:10:10.597655 #53266] ERROR -- default-amazon-linux-hardened: Class: Kitchen::ActionFailed
E, [2018-11-03T23:10:10.597671 #53266] ERROR -- default-amazon-linux-hardened: Message: SCP upload failed (open failed (1))
E, [2018-11-03T23:10:10.597687 #53266] ERROR -- default-amazon-linux-hardened: ----------------------
E, [2018-11-03T23:10:10.597701 #53266] ERROR -- default-amazon-linux-hardened: ------Backtrace-------
E, [2018-11-03T23:10:10.597715 #53266] ERROR -- default-amazon-linux-hardened: /usr/local/lib/ruby/gems/2.5.0/gems/test-kitchen-1.23.2/lib/kitchen/provisioner/base.rb:91:in `rescue in call'
E, [2018-11-03T23:10:10.597730 #53266] ERROR -- default-amazon-linux-hardened: /usr/local/lib/ruby/gems/2.5.0/gems/test-kitchen-1.23.2/lib/kitchen/provisioner/base.rb:67:in `call'
E, [2018-11-03T23:10:10.597744 #53266] ERROR -- default-amazon-linux-hardened: /usr/local/lib/ruby/gems/2.5.0/gems/test-kitchen-1.23.2/lib/kitchen/instance.rb:408:in `block in converge_action'
E, [2018-11-03T23:10:10.597758 #53266] ERROR -- default-amazon-linux-hardened: /usr/local/lib/ruby/gems/2.5.0/gems/test-kitchen-1.23.2/lib/kitchen/instance.rb:551:in `synchronize_or_call'
E, [2018-11-03T23:10:10.597772 #53266] ERROR -- default-amazon-linux-hardened: /usr/local/lib/ruby/gems/2.5.0/gems/test-kitchen-1.23.2/lib/kitchen/instance.rb:513:in `block in action'
E, [2018-11-03T23:10:10.597786 #53266] ERROR -- default-amazon-linux-hardened: /usr/local/Cellar/ruby/2.5.3/lib/ruby/2.5.0/benchmark.rb:293:in `measure'
E, [2018-11-03T23:10:10.597800 #53266] ERROR -- default-amazon-linux-hardened: /usr/local/lib/ruby/gems/2.5.0/gems/test-kitchen-1.23.2/lib/kitchen/instance.rb:512:in `action'
E, [2018-11-03T23:10:10.597824 #53266] ERROR -- default-amazon-linux-hardened: /usr/local/lib/ruby/gems/2.5.0/gems/test-kitchen-1.23.2/lib/kitchen/instance.rb:404:in `converge_action'
E, [2018-11-03T23:10:10.597838 #53266] ERROR -- default-amazon-linux-hardened: /usr/local/lib/ruby/gems/2.5.0/gems/test-kitchen-1.23.2/lib/kitchen/instance.rb:382:in `block (2 levels) in transition_to'
E, [2018-11-03T23:10:10.597850 #53266] ERROR -- default-amazon-linux-hardened: /usr/local/lib/ruby/gems/2.5.0/gems/test-kitchen-1.23.2/lib/kitchen/lifecycle_hooks.rb:45:in `run_with_hooks'
E, [2018-11-03T23:10:10.597862 #53266] ERROR -- default-amazon-linux-hardened: /usr/local/lib/ruby/gems/2.5.0/gems/test-kitchen-1.23.2/lib/kitchen/instance.rb:381:in `block in transition_to'
E, [2018-11-03T23:10:10.597874 #53266] ERROR -- default-amazon-linux-hardened: /usr/local/lib/ruby/gems/2.5.0/gems/test-kitchen-1.23.2/lib/kitchen/instance.rb:380:in `each'
E, [2018-11-03T23:10:10.597886 #53266] ERROR -- default-amazon-linux-hardened: /usr/local/lib/ruby/gems/2.5.0/gems/test-kitchen-1.23.2/lib/kitchen/instance.rb:380:in `transition_to'
E, [2018-11-03T23:10:10.597898 #53266] ERROR -- default-amazon-linux-hardened: /usr/local/lib/ruby/gems/2.5.0/gems/test-kitchen-1.23.2/lib/kitchen/instance.rb:140:in `converge'
E, [2018-11-03T23:10:10.597910 #53266] ERROR -- default-amazon-linux-hardened: /usr/local/lib/ruby/gems/2.5.0/gems/test-kitchen-1.23.2/lib/kitchen/command.rb:197:in `public_send'
E, [2018-11-03T23:10:10.597922 #53266] ERROR -- default-amazon-linux-hardened: /usr/local/lib/ruby/gems/2.5.0/gems/test-kitchen-1.23.2/lib/kitchen/command.rb:197:in `run_action_in_thread'
E, [2018-11-03T23:10:10.597934 #53266] ERROR -- default-amazon-linux-hardened: /usr/local/lib/ruby/gems/2.5.0/gems/test-kitchen-1.23.2/lib/kitchen/command.rb:169:in `block (2 levels) in run_action'
E, [2018-11-03T23:10:10.597946 #53266] ERROR -- default-amazon-linux-hardened: ----End Backtrace-----
E, [2018-11-03T23:10:10.597957 #53266] ERROR -- default-amazon-linux-hardened: ---Nested Exception---
E, [2018-11-03T23:10:10.597969 #53266] ERROR -- default-amazon-linux-hardened: Class: Kitchen::Transport::SshFailed
E, [2018-11-03T23:10:10.597980 #53266] ERROR -- default-amazon-linux-hardened: Message: SCP upload failed (open failed (1))
E, [2018-11-03T23:10:10.597992 #53266] ERROR -- default-amazon-linux-hardened: ----------------------
E, [2018-11-03T23:10:10.598004 #53266] ERROR -- default-amazon-linux-hardened: ------Backtrace-------
E, [2018-11-03T23:10:10.598016 #53266] ERROR -- default-amazon-linux-hardened: /usr/local/lib/ruby/gems/2.5.0/gems/test-kitchen-1.23.2/lib/kitchen/provisioner/base.rb:91:in `rescue in call'
E, [2018-11-03T23:10:10.598027 #53266] ERROR -- default-amazon-linux-hardened: /usr/local/lib/ruby/gems/2.5.0/gems/test-kitchen-1.23.2/lib/kitchen/provisioner/base.rb:67:in `call'
E, [2018-11-03T23:10:10.598039 #53266] ERROR -- default-amazon-linux-hardened: /usr/local/lib/ruby/gems/2.5.0/gems/test-kitchen-1.23.2/lib/kitchen/instance.rb:408:in `block in converge_action'
E, [2018-11-03T23:10:10.598051 #53266] ERROR -- default-amazon-linux-hardened: /usr/local/lib/ruby/gems/2.5.0/gems/test-kitchen-1.23.2/lib/kitchen/instance.rb:551:in `synchronize_or_call'
E, [2018-11-03T23:10:10.598063 #53266] ERROR -- default-amazon-linux-hardened: /usr/local/lib/ruby/gems/2.5.0/gems/test-kitchen-1.23.2/lib/kitchen/instance.rb:513:in `block in action'
E, [2018-11-03T23:10:10.598075 #53266] ERROR -- default-amazon-linux-hardened: /usr/local/Cellar/ruby/2.5.3/lib/ruby/2.5.0/benchmark.rb:293:in `measure'
E, [2018-11-03T23:10:10.598087 #53266] ERROR -- default-amazon-linux-hardened: /usr/local/lib/ruby/gems/2.5.0/gems/test-kitchen-1.23.2/lib/kitchen/instance.rb:512:in `action'
E, [2018-11-03T23:10:10.598099 #53266] ERROR -- default-amazon-linux-hardened: /usr/local/lib/ruby/gems/2.5.0/gems/test-kitchen-1.23.2/lib/kitchen/instance.rb:404:in `converge_action'
E, [2018-11-03T23:10:10.598119 #53266] ERROR -- default-amazon-linux-hardened: /usr/local/lib/ruby/gems/2.5.0/gems/test-kitchen-1.23.2/lib/kitchen/instance.rb:382:in `block (2 levels) in transition_to'
E, [2018-11-03T23:10:10.598132 #53266] ERROR -- default-amazon-linux-hardened: /usr/local/lib/ruby/gems/2.5.0/gems/test-kitchen-1.23.2/lib/kitchen/lifecycle_hooks.rb:45:in `run_with_hooks'
E, [2018-11-03T23:10:10.598144 #53266] ERROR -- default-amazon-linux-hardened: /usr/local/lib/ruby/gems/2.5.0/gems/test-kitchen-1.23.2/lib/kitchen/instance.rb:381:in `block in transition_to'
E, [2018-11-03T23:10:10.598156 #53266] ERROR -- default-amazon-linux-hardened: /usr/local/lib/ruby/gems/2.5.0/gems/test-kitchen-1.23.2/lib/kitchen/instance.rb:380:in `each'
E, [2018-11-03T23:10:10.598167 #53266] ERROR -- default-amazon-linux-hardened: /usr/local/lib/ruby/gems/2.5.0/gems/test-kitchen-1.23.2/lib/kitchen/instance.rb:380:in `transition_to'
E, [2018-11-03T23:10:10.598179 #53266] ERROR -- default-amazon-linux-hardened: /usr/local/lib/ruby/gems/2.5.0/gems/test-kitchen-1.23.2/lib/kitchen/instance.rb:140:in `converge'
E, [2018-11-03T23:10:10.598191 #53266] ERROR -- default-amazon-linux-hardened: /usr/local/lib/ruby/gems/2.5.0/gems/test-kitchen-1.23.2/lib/kitchen/command.rb:197:in `public_send'
E, [2018-11-03T23:10:10.598203 #53266] ERROR -- default-amazon-linux-hardened: /usr/local/lib/ruby/gems/2.5.0/gems/test-kitchen-1.23.2/lib/kitchen/command.rb:197:in `run_action_in_thread'
E, [2018-11-03T23:10:10.598215 #53266] ERROR -- default-amazon-linux-hardened: /usr/local/lib/ruby/gems/2.5.0/gems/test-kitchen-1.23.2/lib/kitchen/command.rb:169:in `block (2 levels) in run_action'
E, [2018-11-03T23:10:10.598227 #53266] ERROR -- default-amazon-linux-hardened: ----End Backtrace-----`

**Comment by b00ga** [comment]
Although I don't use AWS and haven't seen this specific issue, I have had "copying files over ssh issues" with all kinds of weird kitchen failures.

Adding the following to restrict ssh in .kitchen.yml has resolved the issue for me pretty much across the board. Curious if it would help your situation as well.

```
transport:
  name: ssh
  max_ssh_sessions: 2
```

-Shawn

**Comment by proffalken** [comment]
Can confirm that setting the transport options also fixed this issue for me.

**Comment by e-moshaya** [comment]
Closing this as @b00ga suggestion seems to fix this

**Comment by paulcalabro** [comment]
Is there a particular reason why you chose 2? Why not 1 or 3?
