### ISSUE TITLE
converge is failing for 'jmespath' library while using 'json_query' jinja filter

### ISSUE THREAD

**Issue by avishayil** [neillturner/kitchen-ansible#296]
Hi,
As part of the requirements, to use `json_query` jinja filter you need to install `jmespath`
I'm doing this in my `default.yml` playbook. However, `kitchen converge` continues to fail on this 'missing' library even though it's installed.
I tried this way:
- `sudo -E -H pip install` on the `default.yml` playbook, while on the `kitchen.yml` provisioner configuration I specified `sudo_command: sudo -E -H`.
Any ideas how to get this installed properly? in the ansible issues they say it has to be in a place where ansible can reach it.

**Comment by neillturner** [comment]
You can use the custom_pre_install_command to install extra stuff before the ansible install or you can use the custom_post_install_command to install stuff after ansible has been install. 
If its a path issue then use the -l debug option to see what path is  being set and then you maybe able to add extra paths. Other possibility is it is being instakk under root user but then you are running under a non-root user (or visa versa)
