### ISSUE TITLE
ansible.cfg is always overwritten

### ISSUE THREAD

**Issue by MatrixCrawler** [neillturner/kitchen-ansible#297]
We are using a custom docker image for our ansible-tests that is already provided wih an ansible installation and some custom modules that we use. We are providing an /etc/ansible/ansible.cfg in this docker image, that is always overwritten by kitchen-ansible.

we wouldn't like to be forced to add an ansible.cfg to every single role repository we are using (70+).
I think the ansible.cfg should not be overwritten is there is no local ansible.cfg provided.

**Comment by neillturner** [comment]
fixed version 0.49.1
