### ISSUE TITLE
Link/Override module_utils path

### ISSUE THREAD

**Issue by getjack** [neillturner/kitchen-ansible#299]
I'd like to use kitchen-ansible for local module development.
As long as my module_utils *.py is not part of the Ansible project it is entirely missing in the docker container (driver) and i cannot run my module using the code in the utils file.
I think there is a workaround when creating the driver but i'd rather have it supported in this project.

**Comment by neillturner** [comment]
I believe you can use the Test Kitchen Exec Driver to run test kitchen and ansible from your workstation. I refer to this in the README.md.  You application would still be in a docker container though.

**Comment by neillturner** [comment]
closing
