### ISSUE TITLE
Ubuntu 18.04 can't install python-software-properties.

### ISSUE THREAD

**Issue by budgester** [neillturner/kitchen-ansible#300]
__This section does the package check.__

https://github.com/neillturner/kitchen-ansible/blob/master/lib/kitchen/provisioner/ansible/os/debian.rb#L50-L64

__From a ubuntu machine__

ubuntu@ip-172-31-24-232:~$ cat /etc/os-release .
NAME="Ubuntu"
VERSION="18.04.1 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.1 LTS"
VERSION_ID="18.04"

__Warning from the server__

Building dependency tree
Reading state information... Done
       Package python-software-properties is not available, but is referred to by another package.
       This may mean that the package is missing, has been obsoleted, or
       is only available from another source
       However the following packages replace it:
         software-properties-common

       E: Package 'python-software-properties' has no installation candidate

**Comment by neillturner** [comment]
Thanks for reporting. Well when new version of Operating Systems etc are released often a little change here and there needs to be done.

**Comment by neillturner** [comment]
fixed version 0.50.1
