### ISSUE TITLE
Setting `additional_copy_role_path` causes error on second run of `kitchen converge`

### ISSUE THREAD

**Issue by DanHam** [neillturner/kitchen-ansible#304]
I have included an additional role using `additional_copy_role_path`. 

The first issue I have noticed is that the additional role is not copied to `/tmp/kitchen/roles` but is instead copied to `/tmp/kitchen`. 

I have my playbook set as below:

```yml
---
- hosts: localhost
  roles:
    - role: additional_role
    - role: role_i_am_testing
```

The first time I run `kitchen converge` the run completes without error. However, running `kitchen converge` a second time results in a error:

```
       ...
       Transferring files to <default-debian-kitchen-ansible>
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ActionFailed
>>>>>> Message: 1 actions failed.
>>>>>>     Failed to complete #converge action: [scp: /tmp/kitchen/additional_role/somefile: Permission denied
] on default-debian-kitchen-ansible
>>>>>> ----------------------
```

I believe the error occurs because the directory and files already exist on the kitchen instance and scp is refusing to overwrite them. If I login to the kitchen instance and manually remove the `/tmp/kitchen/additional_role` directory then `kitchen converge` runs successfully again - but then fails again on subsequent runs.

I have been able to 'fix' the issue by making a few small changes to `ansible_playbook.rb`. The changes simply ensure the additional role is uploaded to the `/tmp/kitchen/roles` directory. Since this is removed and recreated with each run of kitchen we do not get the error seen above due to the directory already being present on the target instance. 

```diff
--- ansible_playbook.rb 2019-03-23 15:34:51.000000000 +0000
+++ /Users/dan/ansible_playbook.rb      2019-03-23 15:33:54.000000000 +0000
@@ -921,10 +921,10 @@
         roles_paths << File.join(config[:root_path], 'roles') unless config[:roles_path].nil?
         if config[:additional_copy_role_path]
           if config[:additional_copy_role_path].is_a? String
-            roles_paths << File.join(config[:root_path], File.basename(config[:additional_copy_role_path]))
+            roles_paths << File.join(config[:root_path], 'roles', File.basename(config[:additional_copy_role_path]))
           else
             config[:additional_copy_role_path].each do |path|
-              roles_paths << File.join(config[:root_path], File.basename(File.expand_path(path)))
+              roles_paths << File.join(config[:root_path], 'roles', File.basename(File.expand_path(path)))
             end
           end
         end
@@ -952,12 +952,12 @@
         if config[:additional_copy_role_path]
           if config[:additional_copy_role_path].is_a? String
             debug("Using additional roles copy from #{File.expand_path(config[:additional_copy_role_path])}")
-            dest = File.join(sandbox_path, File.basename(File.expand_path(config[:additional_copy_role_path])))
+            dest = File.join(sandbox_path, 'roles', File.basename(File.expand_path(config[:additional_copy_role_path])))
             FileUtils.mkdir_p(File.dirname(dest))
             FileUtils.cp_r(File.expand_path(config[:additional_copy_role_path]), dest)
           else
             config[:additional_copy_role_path].each do |path|
-              dest = File.join(sandbox_path, File.basename(File.expand_path(path)))
+              dest = File.join(sandbox_path, 'roles', File.basename(File.expand_path(path)))
               FileUtils.mkdir_p(File.dirname(dest))
               FileUtils.cp_r(File.expand_path(path), dest)
             end
```

The changes will also means that additional roles are handled in much the same way as the role under test - namely that the role directory is uploaded to `/tmp/kitchen/roles` and that the role is uploaded anew each time `kitchen converge` is run.

I am happy to create a PR if the changes above are deemed acceptable. I haven't done yet as:

* My knowledge of Ruby is not great. The changes above work for me... but there may be a better, more idiomatic way of doing this
* I may have done something stupid to cause the error and no changes are necessary!

**Comment by neillturner** [comment]
create the PR and i will merge and test
