### ISSUE TITLE
CentOS/RHEL 8 support

### ISSUE THREAD

**Issue by petracvv** [neillturner/kitchen-ansible#317]
I've been trying out this plugin on RHEL 8 machines and for the most part it works but I am finding one or two issues:

- When using `require_ansible_repo` it installs EPEL correctly but the actual package installation fails because the `libselinux-python` package is not part of RHEL8. It has been replaced with `python3-libselinux`
- When using `require_pip` it fails to install ansible because there is no generic pip command on RHEL 8. You have to specify pip2 or pip3. In addition, only python3 is installed by default.

There may be other issues I'm missing. Any chance this plugin can be updated to support CentOS/RHEL 8 ?

**Comment by neillturner** [comment]
added require_pip3 option for centos/redhat in version 0.52.0
