### ISSUE TITLE
test-kitchen supporters wanted 

### ISSUE THREAD

**Issue by Xorima** [neillturner/kitchen-ansible#319]
Hi All,

I am one of the admins for https://github.com/test-kitchen and we are looking for additional maintainers to help ensure the direction of the project works for everyone.

Would there be any members of Puppet and/or Ansible who would like to help us here (And ensure it continues to work for your usecases?)

Also thanks for these great provisioners!

Thanks

Jason

**Comment by neillturner** [comment]
Thanks for reaching out to me.  Unfortunately Test Kitchen was a missed opportunity for Chef software as it was folded in the Chef platform instead of being a separate tool that works with lots of products (like Hashicorp do).  Instead ansible, puppet created there own test tools.

**Comment by Xorima** [comment]
Thanks for the response :+1:
