### ISSUE TITLE
Ubuntu 20.04 ppa has no ansible

### ISSUE THREAD

**Issue by budgester** [neillturner/kitchen-ansible#321]
```
Reading package lists... Done                               
       E: The repository 'http://ppa.launchpad.net/ansible/ansible/ubuntu focal Release' does not have a Release file.
       N: Updating from such a repository can't be done securely, and is therefore disabled by default.
       N: See apt-secure(8) manpage for repository creation and user configuration details.
        Ansible is a radically simple IT automation platform that makes your applications and systems easier to deploy. Avoid writing scripts or custom code to deploy and update your applications— automate in a language that approaches plain English, using SSH, with no agents to install on remote systems.
       
       http://ansible.com/
        More info: https://launchpad.net/~ansible/+archive/ubuntu/ansible
       Press [ENTER] to continue or Ctrl-c to cancel adding `it.`

```

However ansible (2.9.6+dfsg-1) is available from the main repo.

**Comment by budgester** [comment]
Referenced https://github.com/ansible/ansible/pull/69161

**Comment by sumodirjo** [comment]
I tried changing the `ansible_apt_repo` variable value to `''` and my test can run on Focal.

My understanding is that kitchen-ansible will install ansible from the Ubuntu repository. There is a potential problem that ansible version between ubuntu release is different. So the test might be run with different ansible on different Ubuntu releases.

**Comment by neillturner** [comment]
by default require_ansible_repo is set to true and it Installs from the operation system repository only with the ansible version. 
in ubuntu's case this is the 

ansible_apt_repo parameter   ppa:ansible/ansible

this looks like an issue with ansible and ubuntu https://github.com/ansible/ansible/issues/69414

https://github.com/geerlingguy/packer-boxes/issues/63
he got around by installing with pip3 so i suggest you use 
set in kitchen.yml require_pip3  to true and install that way.

**Comment by olhado** [comment]
So I have an ansible role that I want to run tests on, across multiple versions of ubuntu (16.04, 18.04, 20.04). @sumodirjo's workaround doesn't work for me, because I don't want to skip over the official ppa package for the older LTS releases. I have an MR (#324) that works around the current issues for now, which can be removed if ansible ever supports it.

I verified with kitchen-docker that ubuntu 16.04, 18.04, and 20.04 can all run my role successfully.
