### ISSUE TITLE
Does it support "include" other playboooks in suite playbook 

### ISSUE THREAD

**Issue by mcasado** [neillturner/kitchen-ansible#33]
I'm using include : include: "postgres.yml" in the suite playbook but I get  ERROR: file could not read: /tmp/kitchen/postgres.yml

**Comment by neillturner** [comment]
No. 
check the info at https://github.com/neillturner/kitchen-ansible/issues/10
all files need to be relative to the playbook directory

**Comment by neillturner** [comment]
closing
