### ISSUE TITLE
Can't run rspec tests

### ISSUE THREAD

**Issue by apenney** [neillturner/kitchen-ansible#35]
Hi,

I've been trying to get the tests working so that I can add a couple of features (vault support, arbitary files rather than a directory) but I've been unable to fix:

```
  1) Kitchen::Provisioner::AnsiblePlaybook#run_command should give a sane run_command
     Failure/Error: expect(provisioner.run_command).to match(/ansible-playbook/)
     NoMethodError:
       undefined method `suite' for nil:NilClass
```

I've tried a dozen things to make this work, from trying to mock out an instance that takes in the provisioner we create in the test to copying whole chunks up how test-kitchen tests the base provider, but I've been unable to get it to work properly.

Can you see if tests still work for you? I suspect it's because without a Gemfile I pulled in rspec 3.2 and that's just broken with the current tests.

**Comment by apenney** [comment]
(I just made sure with rspec 2.99.2 and it's broken there too)

**Comment by neillturner** [comment]
I'm away this week but will try to.make some time next week.to
Look. Often with ruby new version of dependent gem cause breakages
