### ISSUE TITLE
ansiable can't be installed on Vagrant host in README

### ISSUE THREAD

**Issue by bscott** [neillturner/kitchen-ansible#36]
epel/primary_db                                          | 6.5 MB     00:08
       Setting up Install Process
       No package ansible-1.6.2-1.el6 available.
       Package libselinux-python-2.0.94-5.8.el6.x86_64 already installed and latest version
       Nothing to do
       Transfering files to <default-nocm-centos-65>
       sudo: ansible-playbook: command not found

**Comment by neillturner** [comment]
there area couple of parameters you can configure as per 
https://github.com/neillturner/kitchen-ansible/blob/master/provisioner_options.md

ansible_version
require_ansible_repo 
ansible_yum_repo

on redhat by default it installs from 
https://download.fedoraproject.org/pub/epel/6/i386/epel-release-6-8.noarch.rpm
you need the epel repository for this to work. 
google "install redhat epel 6" 
and make sure that the epel is installed. 

if this does not fix it have a look at
  http://docs.ansible.com/intro_installation.html
and maybe try and install from yum maunally on the box under vagrant. 
if you look at the code for redhat it does:
  #{sudo('rpm')} -ivh #{ansible_yum_repo}
  #{sudo('yum')} makecache
  #{sudo('yum')} -y install ansible#{ansible_redhat_version} libselinux-python
try and manually on the box  do the commands and debug it.

**Comment by neillturner** [comment]
closing this as i believe most os platforms are now installable
