### ISSUE TITLE
Define multiple locations for role locations

### ISSUE THREAD

**Issue by metmajer** [neillturner/kitchen-ansible#38]
Can anyone think of a way to explicitly or implicitly define multiple locations for roles?

Example: In my integration test I want to apply various roles that make up the test environment before the actual role under test is applied. A particular use-case would be to install a PostgreSQL database that our application could immediately talk to if configured correctly during installation.

Of course, these supporting roles should not be together with the actual role under test, but rather in *test/integration/roles* (or similar). However, if I do that, the role under test which resides in *roles* will be ignored.

Thanks, Martin

**Comment by trumant** [comment]
@metmajer - I've had to do this before as well. I have used requirements.yml to source the roles using Ansible galaxy. You'll need to include:

```yml
requirements_path: "Path to your requirements.yml"
```

in your kitchen.yml and then also include those roles in your playbook under test/integration

**Comment by metmajer** [comment]
Thanks @trumant!

A *requirements.yml* is a good option! Still looking for something that I could bundle that would always be in place offline. Any other ideas?

Thanks! Martin

**Comment by neillturner** [comment]
closing as question and answer
