### ISSUE TITLE
additional_copy_path should work with files as well as folders

### ISSUE THREAD

**Issue by dgorst** [neillturner/kitchen-ansible#54]
Hey,

I'm writing up some tests for a Playbook that includes a couple of other Playbooks. The Ansible provisioner currently only copies across the playbook I'd like to test, not everything else it depends on...

I'd like to use the *additional_copy_path* param to copy across the additional Playbooks, but it currently only works with directories - from **ansible_playbook.rb**:

```ruby
        def prepare_addt_dir
          info('Preparing additional_copy_path')

          additional_dirs.each do |additional_dir|

            tmp_addt_dir = File.join(sandbox_path, File.basename(additional_dir))
            FileUtils.mkdir_p(tmp_addt_dir)

            unless File.directory?(additional_dir)
              info "invalid value #{additional_dir} in additional_copy_path"
              return
            end

            debug("Using additional_copy_path from #{additional_dir}")
            FileUtils.cp_r(Dir.glob("#{additional_dir}/*"), tmp_addt_dir)
          end
        end
```

I'm happy to raise a PR to get this working with both files and directories, but want to check if there would be any objections or if there's a hard reason for only accepting directories? Or perhaps there's a preferred way of handling this?

Thanks!!

**Comment by neillturner** [comment]
I think we have been here before with issue https://github.com/neillturner/kitchen-ansible/issues/10. 
generally the architecture of test kitchen is to 
- copy specific folders from your repo to the remote server 
- run librarian on your workstation to get all the external roles and pass then as well. 
- use curl or wget in your playbook to download any install files from the internet 
I guess the additional copy path could be a full path instead of a relative path....

**Comment by dgorst** [comment]
Thanks for taking a look @neillturner 

Yeah, I get the pattern is to create a sandbox folder locally and transfer that to the target - but I don't see anything in the Test Kitchen APIs (specifically the `Kitchen::Provisioner::Base.create_sandbox`) that places any limitations on how you might chose to construct that sandbox in a specific provisioner implementation. Having the Ansible provisioner only accept folders in its `additional_copy_path` config and not files seems place an arbitrary limitation on what you can use this to test - it rules out perfectly valid Playbooks... 

`prepare_addt_dir` doesn't really need to limit itself to folders does it?  

Perhaps best I raise a pull request so you can take a look at what I'm suggesting - I'll pop one over today if I get a chance...

**Comment by neillturner** [comment]
thanks for writing this. I close for now.
