### ISSUE TITLE
Ansible galaxy support fails when git is not on the TestKitchen box

### ISSUE THREAD

**Issue by trumant** [neillturner/kitchen-ansible#59]
If you are using the Ansible Galaxy support and specify a git/github repo in your requirements.yml file and the box being used to execute the tests does not have git installed, the TestKitchen run will fail.

This makes some sense, but the error message you will get will be pretty cryptic.

May be worth adding a warning log message or something within kitchen-ansible or possibly just install git on the box along with everything else that the gem ends up installing.

**Comment by trumant** [comment]
Turns out that kitchen-vagrant has some nice customization options that I was unaware of. Specifically, you can configure the kitchen-vagrant driver like so:

```yml
driver:
  name: vagrant
  provision: true
  vagrantfiles: 
    - Vagrantfile.rb
```

Which will have the effect of running vagrant provisioners defined in the TestKitchen Vagrantfile that is created. Any customizations you want to add to the default kitchen-vagrant Vagrantfile can be placed in Vagrantfile.rb and will be merged in when ```vagrant up``` is run.

**Comment by neillturner** [comment]
I was reluctant to automatically install git automatically as it is only needed to this case. Also often the git in the standard repos are pretty old and folks make want newer versions. 
 I can document this and maybe add a parameter install_git and set to false.

**Comment by neillturner** [comment]
i have added git to the install so will out in 0.0.17
