### ISSUE TITLE
Publish 0.17 or 0.18 to Ruby Gems

### ISSUE THREAD

**Issue by trumant** [neillturner/kitchen-ansible#60]
@neillturner - I'd love to get it pushed out there so more people can take advantage of the work to remove the Chef omnibus install.

Of course, this is still an option in the meantime:

```
gem "kitchen-ansible", :git => "https://github.com/neillturner/kitchen-ansible.git", :ref => "c773ba2ba41a4bd3fb7fccdb1d3c84db65a38d92"
```

**Comment by neillturner** [comment]
hopefully i will test and fix today

**Comment by neillturner** [comment]
should release tomorrow so closing
