### ISSUE TITLE
Master broken

### ISSUE THREAD

**Issue by trumant** [neillturner/kitchen-ansible#62]
With bug:

```undefined local variable or method `require_ruby_for_busser' for #<Kitchen::Provisioner::AnsiblePlaybook```

Presumably a result of the configuration refactor happening out of band with the ruby install work. Interestingly rspec tests pass.

**Comment by trumant** [comment]
I've gotten past that locally in hopes of developing a fix, but am now running into:

```
undefined method `sudo_env' for #<Kitchen::Provisioner::AnsiblePlaybook
```

Looks like Kitchen::Provisioner::Base defines ```sudo```, but not ```sudo_env```

**Comment by neillturner** [comment]
well i had to do a manual merge so not surprised. hopefully i will test today.  the code is only a few hundred lines so its not rocket science. sudo_env is in my code. i'll look at it. -)

**Comment by neillturner** [comment]
ok fixed now so will release tomorrow. want to also get amazon linux working but will have to wait.
using http_proxies is not working though.

**Comment by neillturner** [comment]
fixed

**Comment by trumant** [comment]
Thanks @neillturner 

Saw your fix, I was tempted to go the same route, but was headed out the door when I ran into the issue.
