### ISSUE TITLE
Conditional include is failing

### ISSUE THREAD

**Issue by alop** [neillturner/kitchen-ansible#69]
Setting a boolean in defaults to False,
A task then conditionally includes another task when the var is True.
`kitchen test` always tries to include the second task.

in defaults/main.yml
rabbitmq_cluster: false

in tasks/main.yml
- include: cluster.yml
  when: rabbitmq_cluster

Debug output
 ok: [localhost] => {
           "rabbitmq_cluster": "False"
       }
       
       TASK: [cisco.rabbitmq | add controllers to /etc/hosts] ************************ 
       fatal: [localhost] => with_items expects a list or a set
This failed task is the first line in the cluster.yml that should not have been included

**Comment by trinitronx** [comment]
This looks like something that's happening inside Ansible, and is not a bug in `kitchen-ansible`.  When you do a conditional include of `foo.yml` in Ansible, it doesn't seem to completely skip loading the included `tasks/foo.yml` parsing and evaluating it.  So any syntax errors that may be present in this file (whether it's getting included & run this time or not) can cause errors.  You can verify that Ansible actually loads the conditional include by setting your condition to false, then noticing that the task names in that file are still being output except with "`skipping: [hostname]`".

To address your problem:

It appears that you've probably used a variable in a `with_items` statement that is not a list type, and Ansible is spitting out an error.  Although this statement is not going to be "included" in the Ansible run, it will still be evaluated but just "skipped".

**Comment by alop** [comment]
Thanks, that makes sense.

**Comment by neillturner** [comment]
thanks trinitronx for your comments
