### ISSUE TITLE
Ruby already installed on Centos-boxes - symlinking fails

### ISSUE THREAD

**Issue by rndmh3ro** [neillturner/kitchen-ansible#81]
When another version of ruby is already installed on a centos or RHEL box, the symlinking [here](https://github.com/neillturner/kitchen-ansible/blob/master/lib/kitchen/provisioner/ansible_playbook.rb#L135-L136) will fail.

Then the existing ruby-installation should be removed before symlinking, like this:

```
echo "-----> Delete already existing ruby-version so they do not intefere with ruby193"
sudo('yum')} remove -y ruby rubygems     
```

Problem then is that facter also gets removed.

**Comment by neillturner** [comment]
Try setting the require_ruby_for_busser to false in your kitchen.yml file

**Comment by rndmh3ro** [comment]
Thanks, that did it.
