### ISSUE TITLE
SSH key to pull private repo on git

### ISSUE THREAD

**Issue by Seraf** [neillturner/kitchen-ansible#87]
Hello,

My requirement files is using a private repository. The problem is I don't have the private key on my test instance, and the repository is not trusted (need to add the line in known hosts).

Any idea how could it be done ?
Not sure it's related to kitchen-ansible, but it's (I think) a good feature to have.

Thanks

**Comment by neillturner** [comment]
i assume your trying to access git in the server running ansible. 
ssh requirements can be complex but are well documented. 
Sorry if this is a bit patronizing but i would go onto the box and manually run the git command with ssh, get the error and figure out how to fix.  
if you figure out i would fork the omnibus-ansible script and add the  change to the script. 
if you are not using the omnibus-ansible script then we can add some more parameters. -)

**Comment by Seraf** [comment]
Hello,
Thanks for your answer.

Yes, the goal is to clone a role with git using the requirement file.
I'm using docker. I saw that vagrant allow to use a custom ssh key but we can't custom the known host. I search some docs about configuring ssh on the target host but didn't found something relevant.

Anyway, in order to poll the requirement file installed with ansible-glaxy, I need the possibility to configure content or upload 2 files : 

* $HOME/.ssh/id_rsa => to poll my private repository
* $HOME/.ssh/known_hosts => to don't have the prompt (yes/no) when connecting through ssh

As it seems (I can be wrong) to not be a common feature for all drivers, it can be great to support it on kitchen-ansible as it can be used by ansible-galaxy

**Comment by neillturner** [comment]
i don't see why you should not be able to add this to the omnibus ansible install script. my understanding is that configuring these items in ssh is dynamic so after the change you should be able to use them immediately.

**Comment by Seraf** [comment]
@neillturner by "adding to omnibus ansible", you mean fork the script and add my own stuff in the script ?

**Comment by neillturner** [comment]
yes and change the omnibus_download_url to your fork. -)

**Comment by Seraf** [comment]
@neillturner ok, thanks. I was hoping to a "local solution" as my credentials will appears on a public link. I can expose them  behind a basic auth, but it requires a server to do that :)

Anyway thanks, seems a good solution to me.

**Comment by neillturner** [comment]
that's true. we can specify another parameter or 2 passing the credentials from a local file.

**Comment by trinitronx** [comment]
@Seraf: If the issue is what I think it is, you may be able to solve it via [`ssh-agent` forwarding][1]

This way, `test-kitchen` will ssh into the vagrant VM with the `-A` option to ssh.  This effectively creates a local unix socket file that will point back to the running instance of `ssh-agent` on the vagrant host (or whichever host is running `kitchen test`.  The way this works is that some magic `SSH_*` environment vars get set inside the Vagrant VM when `ssh -A` is run.  This way the Vagrant VM can connect back to the running `ssh-agent` process that is running outside the VM on the host that ran `ssh -A` and can interrogate the `ssh-agent` with a key challenge/response to use it for authentication.  The private keys should always remain secure inside `ssh-agent`, and will only be used to authenticate ssh connections / hops to other servers from the host you have connected to with [SSH Agent Forwarding][2].



[1]: https://github.com/test-kitchen/kitchen-vagrant/issues/27#issuecomment-40280166
[2]: http://www.unixwiz.net/techtips/ssh-agent-forwarding.html

**Comment by Seraf** [comment]
oh, thanks @trinitronx I think it will do the job.

Thanks you both for the support !

**Comment by Seraf** [comment]
@trinitronx have you tried this solution without a known_hosts file ? It's stuck on the (yes/no) prompt.
I tried to give the argument "user_known_hosts_file: /home/seraf/.ssh/known_hosts" but without any success.

**Comment by neillturner** [comment]
@Seraf it should be possible to use a custom omnibus install script without making it public. 
customize the ansible_install.sh and put it inside your ansible ansible repo somewhere so it gets copied. 
then for the omnibus ansible download url use file://tmp/kitchen/<location>/ansible_install.sh

**Comment by trinitronx** [comment]
@Seraf: there should be a way to add extra options to ssh also to avoid the `known_hosts` prompt.  Usually the options used are: `-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null`

**Comment by bborysenko** [comment]
@Seraf take a look for #123. With 0.0.36 not it's possible without custom omnibus install script!

**Comment by emoshaya-cognito** [comment]
I'm facing the exact same issue now... I'm using requirements.yml to install depedencies that are hosted on private git repositories. However, the ~/.ssh/id_rsa is missing on the test kitchen host.. Is there a way for the provisioner to copy the local ~/.ssh/id_rsa to the target kitchen's host's ~/.ssh/id_rsa?

**Comment by neillturner** [comment]
i will look at how to do this

**Comment by neillturner** [comment]
additional_ssh_private_keys parameter in version 0.46.3

**Comment by EugenMayer** [comment]
@neillturner one of the issues with the `additional_ssh_private_keys`  parameters are permissions. e.g. with kitchen ansible docker, you usually end up having the root user to run the ansible provision ( thus this runs the copy command ) but the ansible user will be `kitchen` - the key will then be `root:root` and will not be useable

Did anybody actually got SSH-forward to work? adding this

```
[ssh_connection]
ssh_args = -o ForwardAgent=yes -o ControlMaster=auto -o ControlPersist=30m UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no
```

to my ansible.cfg did not help me here. any hints?

**Comment by EugenMayer** [comment]
Sorry to basically instantly answering my own question - maybe this helps others. In the case of ktichen docker/kitchen vagrant it seems that using the suggested variant with `ansible.cfg` like

```
[ssh_connection]
ssh_args = -o ForwardAgent=yes -o ControlMaster=auto -o ControlPersist=30m UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no
```

Will not work.

Though this works added to the `.kitchen.yml`

```yaml
...
suites:
  - name: default
    verifier:
      inspec_tests:
        - test/integration/default/inspec/

# thats the import part
transport:
  forward_agent: true
```

So before running

```bash
chef exec bundle exec kitchen test
```

you run this once, adding your `id_rsa` key ( or others ) to your ssh agent

```bash
ssh-agent
```
