### ISSUE TITLE
Add argument for custom inventory file

### ISSUE THREAD

**Issue by iwfmp** [neillturner/kitchen-ansible#9]
I want to specify a custom hosts (inventory) file using the .kitchen.yml.
is that possible?

it is the same as specifiying ansible-playbook -i custom_hosts
instead of it taking the default hosts file

**Comment by trinitronx** [comment]
@iwfmp:  I was thinking about a way to implement this using an embedded ansible playbook fixture directory that contains `inventory/hosts` which would then be used by the `run_command` inside the VM to run `ansible-playbook -i /tmp/kitchen/inventory/hosts`.  However, lack of time prevented me from completing this.

**Comment by neillturner** [comment]
My understand is this allows multiple host support. Currently I'm just trying to run ansible on the box itself. Maybe in the fullness of time this could be looked at but I'm closing as I think this is out of scope currently.
