### ISSUE TITLE
How to run idempotence test for ansible role via Test-Kitchen?

### ISSUE THREAD

**Issue by strangeman** [neillturner/kitchen-ansible#92]
Is there a way to run idempotence test: run playbook second time and check that items have not changed. It is pretty easy with Travis, but I don't know how to do that with kitchen+ansible_playbook provider.

I created a question on StackOverflow - http://stackoverflow.com/questions/32473572/how-to-run-idempotence-test-for-ansible-role-via-test-kitchen, but have no luck.

**Comment by strangeman** [comment]
Solved for myself with BATS test:

```#!/usr/bin/env bats
#

#
# Idempotence test
#

@test "Second run should change nothing" {
    run bash -c "ansible-playbook -i /tmp/kitchen/hosts /tmp/kitchen/default.yml -c local | grep -q 'changed=0.*failed=0' && exit 0 || exit 1"
    [ "$status" -eq 0 ]
}```

**Comment by trinitronx** [comment]
good thinking!  You could also probably do the same with serverspec's [`command` resource type](http://serverspec.org/resource_types.html#command).  

```ruby
describe command('ls -al /') do
  its(:stdout) { should match /bin/ }
end

describe command('ansible-playbook -i /tmp/kitchen/hosts /tmp/kitchen/default.yml -c local') do
  its(:stderr) { should match /changed=0.*failed=0/ }

  its(:exit_status) { should eq 0 }
end
```
